// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/map/relative_map/proto/relative_map_config.proto

#ifndef PROTOBUF_INCLUDED_modules_2fmap_2frelative_5fmap_2fproto_2frelative_5fmap_5fconfig_2eproto
#define PROTOBUF_INCLUDED_modules_2fmap_2frelative_5fmap_2fproto_2frelative_5fmap_5fconfig_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fmap_2frelative_5fmap_2fproto_2frelative_5fmap_5fconfig_2eproto 

namespace protobuf_modules_2fmap_2frelative_5fmap_2fproto_2frelative_5fmap_5fconfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_modules_2fmap_2frelative_5fmap_2fproto_2frelative_5fmap_5fconfig_2eproto
namespace apollo {
namespace relative_map {
class MapGenerationParam;
class MapGenerationParamDefaultTypeInternal;
extern MapGenerationParamDefaultTypeInternal _MapGenerationParam_default_instance_;
class NavigationLaneConfig;
class NavigationLaneConfigDefaultTypeInternal;
extern NavigationLaneConfigDefaultTypeInternal _NavigationLaneConfig_default_instance_;
class RelativeMapConfig;
class RelativeMapConfigDefaultTypeInternal;
extern RelativeMapConfigDefaultTypeInternal _RelativeMapConfig_default_instance_;
}  // namespace relative_map
}  // namespace apollo
namespace google {
namespace protobuf {
template<> ::apollo::relative_map::MapGenerationParam* Arena::CreateMaybeMessage<::apollo::relative_map::MapGenerationParam>(Arena*);
template<> ::apollo::relative_map::NavigationLaneConfig* Arena::CreateMaybeMessage<::apollo::relative_map::NavigationLaneConfig>(Arena*);
template<> ::apollo::relative_map::RelativeMapConfig* Arena::CreateMaybeMessage<::apollo::relative_map::RelativeMapConfig>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace apollo {
namespace relative_map {

enum NavigationLaneConfig_LaneSource {
  NavigationLaneConfig_LaneSource_PERCEPTION = 1,
  NavigationLaneConfig_LaneSource_OFFLINE_GENERATED = 2
};
bool NavigationLaneConfig_LaneSource_IsValid(int value);
const NavigationLaneConfig_LaneSource NavigationLaneConfig_LaneSource_LaneSource_MIN = NavigationLaneConfig_LaneSource_PERCEPTION;
const NavigationLaneConfig_LaneSource NavigationLaneConfig_LaneSource_LaneSource_MAX = NavigationLaneConfig_LaneSource_OFFLINE_GENERATED;
const int NavigationLaneConfig_LaneSource_LaneSource_ARRAYSIZE = NavigationLaneConfig_LaneSource_LaneSource_MAX + 1;

const ::google::protobuf::EnumDescriptor* NavigationLaneConfig_LaneSource_descriptor();
inline const ::std::string& NavigationLaneConfig_LaneSource_Name(NavigationLaneConfig_LaneSource value) {
  return ::google::protobuf::internal::NameOfEnum(
    NavigationLaneConfig_LaneSource_descriptor(), value);
}
inline bool NavigationLaneConfig_LaneSource_Parse(
    const ::std::string& name, NavigationLaneConfig_LaneSource* value) {
  return ::google::protobuf::internal::ParseNamedEnum<NavigationLaneConfig_LaneSource>(
    NavigationLaneConfig_LaneSource_descriptor(), name, value);
}
// ===================================================================

class MapGenerationParam : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.relative_map.MapGenerationParam) */ {
 public:
  MapGenerationParam();
  virtual ~MapGenerationParam();

  MapGenerationParam(const MapGenerationParam& from);

  inline MapGenerationParam& operator=(const MapGenerationParam& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MapGenerationParam(MapGenerationParam&& from) noexcept
    : MapGenerationParam() {
    *this = ::std::move(from);
  }

  inline MapGenerationParam& operator=(MapGenerationParam&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MapGenerationParam& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MapGenerationParam* internal_default_instance() {
    return reinterpret_cast<const MapGenerationParam*>(
               &_MapGenerationParam_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MapGenerationParam* other);
  friend void swap(MapGenerationParam& a, MapGenerationParam& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MapGenerationParam* New() const final {
    return CreateMaybeMessage<MapGenerationParam>(NULL);
  }

  MapGenerationParam* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MapGenerationParam>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MapGenerationParam& from);
  void MergeFrom(const MapGenerationParam& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MapGenerationParam* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double default_left_width = 1 [default = 1.75];
  bool has_default_left_width() const;
  void clear_default_left_width();
  static const int kDefaultLeftWidthFieldNumber = 1;
  double default_left_width() const;
  void set_default_left_width(double value);

  // optional double default_right_width = 2 [default = 1.75];
  bool has_default_right_width() const;
  void clear_default_right_width();
  static const int kDefaultRightWidthFieldNumber = 2;
  double default_right_width() const;
  void set_default_right_width(double value);

  // optional double default_speed_limit = 3 [default = 29.0576];
  bool has_default_speed_limit() const;
  void clear_default_speed_limit();
  static const int kDefaultSpeedLimitFieldNumber = 3;
  double default_speed_limit() const;
  void set_default_speed_limit(double value);

  // @@protoc_insertion_point(class_scope:apollo.relative_map.MapGenerationParam)
 private:
  void set_has_default_left_width();
  void clear_has_default_left_width();
  void set_has_default_right_width();
  void clear_has_default_right_width();
  void set_has_default_speed_limit();
  void clear_has_default_speed_limit();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  double default_left_width_;
  double default_right_width_;
  double default_speed_limit_;
  friend struct ::protobuf_modules_2fmap_2frelative_5fmap_2fproto_2frelative_5fmap_5fconfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NavigationLaneConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.relative_map.NavigationLaneConfig) */ {
 public:
  NavigationLaneConfig();
  virtual ~NavigationLaneConfig();

  NavigationLaneConfig(const NavigationLaneConfig& from);

  inline NavigationLaneConfig& operator=(const NavigationLaneConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NavigationLaneConfig(NavigationLaneConfig&& from) noexcept
    : NavigationLaneConfig() {
    *this = ::std::move(from);
  }

  inline NavigationLaneConfig& operator=(NavigationLaneConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NavigationLaneConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NavigationLaneConfig* internal_default_instance() {
    return reinterpret_cast<const NavigationLaneConfig*>(
               &_NavigationLaneConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(NavigationLaneConfig* other);
  friend void swap(NavigationLaneConfig& a, NavigationLaneConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NavigationLaneConfig* New() const final {
    return CreateMaybeMessage<NavigationLaneConfig>(NULL);
  }

  NavigationLaneConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NavigationLaneConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NavigationLaneConfig& from);
  void MergeFrom(const NavigationLaneConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NavigationLaneConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef NavigationLaneConfig_LaneSource LaneSource;
  static const LaneSource PERCEPTION =
    NavigationLaneConfig_LaneSource_PERCEPTION;
  static const LaneSource OFFLINE_GENERATED =
    NavigationLaneConfig_LaneSource_OFFLINE_GENERATED;
  static inline bool LaneSource_IsValid(int value) {
    return NavigationLaneConfig_LaneSource_IsValid(value);
  }
  static const LaneSource LaneSource_MIN =
    NavigationLaneConfig_LaneSource_LaneSource_MIN;
  static const LaneSource LaneSource_MAX =
    NavigationLaneConfig_LaneSource_LaneSource_MAX;
  static const int LaneSource_ARRAYSIZE =
    NavigationLaneConfig_LaneSource_LaneSource_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  LaneSource_descriptor() {
    return NavigationLaneConfig_LaneSource_descriptor();
  }
  static inline const ::std::string& LaneSource_Name(LaneSource value) {
    return NavigationLaneConfig_LaneSource_Name(value);
  }
  static inline bool LaneSource_Parse(const ::std::string& name,
      LaneSource* value) {
    return NavigationLaneConfig_LaneSource_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .apollo.relative_map.NavigationLaneConfig.LaneSource lane_source = 2;
  bool has_lane_source() const;
  void clear_lane_source();
  static const int kLaneSourceFieldNumber = 2;
  ::apollo::relative_map::NavigationLaneConfig_LaneSource lane_source() const;
  void set_lane_source(::apollo::relative_map::NavigationLaneConfig_LaneSource value);

  // optional double min_lane_marker_quality = 1 [default = 0.5];
  bool has_min_lane_marker_quality() const;
  void clear_min_lane_marker_quality();
  static const int kMinLaneMarkerQualityFieldNumber = 1;
  double min_lane_marker_quality() const;
  void set_min_lane_marker_quality(double value);

  // optional double max_len_from_navigation_line = 3 [default = 250];
  bool has_max_len_from_navigation_line() const;
  void clear_max_len_from_navigation_line();
  static const int kMaxLenFromNavigationLineFieldNumber = 3;
  double max_len_from_navigation_line() const;
  void set_max_len_from_navigation_line(double value);

  // optional double min_len_for_navigation_lane = 4 [default = 150];
  bool has_min_len_for_navigation_lane() const;
  void clear_min_len_for_navigation_lane();
  static const int kMinLenForNavigationLaneFieldNumber = 4;
  double min_len_for_navigation_lane() const;
  void set_min_len_for_navigation_lane(double value);

  // optional double max_len_for_navigation_lane = 5 [default = 250];
  bool has_max_len_for_navigation_lane() const;
  void clear_max_len_for_navigation_lane();
  static const int kMaxLenForNavigationLaneFieldNumber = 5;
  double max_len_for_navigation_lane() const;
  void set_max_len_for_navigation_lane(double value);

  // optional double ratio_navigation_lane_len_to_speed = 6 [default = 8];
  bool has_ratio_navigation_lane_len_to_speed() const;
  void clear_ratio_navigation_lane_len_to_speed();
  static const int kRatioNavigationLaneLenToSpeedFieldNumber = 6;
  double ratio_navigation_lane_len_to_speed() const;
  void set_ratio_navigation_lane_len_to_speed(double value);

  // optional double max_distance_to_navigation_line = 7 [default = 15];
  bool has_max_distance_to_navigation_line() const;
  void clear_max_distance_to_navigation_line();
  static const int kMaxDistanceToNavigationLineFieldNumber = 7;
  double max_distance_to_navigation_line() const;
  void set_max_distance_to_navigation_line(double value);

  // optional double min_view_range_to_use_lane_marker = 8 [default = 0.5];
  bool has_min_view_range_to_use_lane_marker() const;
  void clear_min_view_range_to_use_lane_marker();
  static const int kMinViewRangeToUseLaneMarkerFieldNumber = 8;
  double min_view_range_to_use_lane_marker() const;
  void set_min_view_range_to_use_lane_marker(double value);

  // optional double min_lane_half_width = 9 [default = 1.5];
  bool has_min_lane_half_width() const;
  void clear_min_lane_half_width();
  static const int kMinLaneHalfWidthFieldNumber = 9;
  double min_lane_half_width() const;
  void set_min_lane_half_width(double value);

  // optional double max_lane_half_width = 10 [default = 2];
  bool has_max_lane_half_width() const;
  void clear_max_lane_half_width();
  static const int kMaxLaneHalfWidthFieldNumber = 10;
  double max_lane_half_width() const;
  void set_max_lane_half_width(double value);

  // optional double lane_marker_weight = 11 [default = 0.1];
  bool has_lane_marker_weight() const;
  void clear_lane_marker_weight();
  static const int kLaneMarkerWeightFieldNumber = 11;
  double lane_marker_weight() const;
  void set_lane_marker_weight(double value);

  // @@protoc_insertion_point(class_scope:apollo.relative_map.NavigationLaneConfig)
 private:
  void set_has_min_lane_marker_quality();
  void clear_has_min_lane_marker_quality();
  void set_has_lane_source();
  void clear_has_lane_source();
  void set_has_max_len_from_navigation_line();
  void clear_has_max_len_from_navigation_line();
  void set_has_min_len_for_navigation_lane();
  void clear_has_min_len_for_navigation_lane();
  void set_has_max_len_for_navigation_lane();
  void clear_has_max_len_for_navigation_lane();
  void set_has_ratio_navigation_lane_len_to_speed();
  void clear_has_ratio_navigation_lane_len_to_speed();
  void set_has_max_distance_to_navigation_line();
  void clear_has_max_distance_to_navigation_line();
  void set_has_min_view_range_to_use_lane_marker();
  void clear_has_min_view_range_to_use_lane_marker();
  void set_has_min_lane_half_width();
  void clear_has_min_lane_half_width();
  void set_has_max_lane_half_width();
  void clear_has_max_lane_half_width();
  void set_has_lane_marker_weight();
  void clear_has_lane_marker_weight();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  int lane_source_;
  double min_lane_marker_quality_;
  double max_len_from_navigation_line_;
  double min_len_for_navigation_lane_;
  double max_len_for_navigation_lane_;
  double ratio_navigation_lane_len_to_speed_;
  double max_distance_to_navigation_line_;
  double min_view_range_to_use_lane_marker_;
  double min_lane_half_width_;
  double max_lane_half_width_;
  double lane_marker_weight_;
  friend struct ::protobuf_modules_2fmap_2frelative_5fmap_2fproto_2frelative_5fmap_5fconfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RelativeMapConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.relative_map.RelativeMapConfig) */ {
 public:
  RelativeMapConfig();
  virtual ~RelativeMapConfig();

  RelativeMapConfig(const RelativeMapConfig& from);

  inline RelativeMapConfig& operator=(const RelativeMapConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RelativeMapConfig(RelativeMapConfig&& from) noexcept
    : RelativeMapConfig() {
    *this = ::std::move(from);
  }

  inline RelativeMapConfig& operator=(RelativeMapConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RelativeMapConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RelativeMapConfig* internal_default_instance() {
    return reinterpret_cast<const RelativeMapConfig*>(
               &_RelativeMapConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(RelativeMapConfig* other);
  friend void swap(RelativeMapConfig& a, RelativeMapConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RelativeMapConfig* New() const final {
    return CreateMaybeMessage<RelativeMapConfig>(NULL);
  }

  RelativeMapConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RelativeMapConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RelativeMapConfig& from);
  void MergeFrom(const RelativeMapConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RelativeMapConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.relative_map.MapGenerationParam map_param = 1;
  bool has_map_param() const;
  void clear_map_param();
  static const int kMapParamFieldNumber = 1;
  private:
  const ::apollo::relative_map::MapGenerationParam& _internal_map_param() const;
  public:
  const ::apollo::relative_map::MapGenerationParam& map_param() const;
  ::apollo::relative_map::MapGenerationParam* release_map_param();
  ::apollo::relative_map::MapGenerationParam* mutable_map_param();
  void set_allocated_map_param(::apollo::relative_map::MapGenerationParam* map_param);

  // optional .apollo.relative_map.NavigationLaneConfig navigation_lane = 2;
  bool has_navigation_lane() const;
  void clear_navigation_lane();
  static const int kNavigationLaneFieldNumber = 2;
  private:
  const ::apollo::relative_map::NavigationLaneConfig& _internal_navigation_lane() const;
  public:
  const ::apollo::relative_map::NavigationLaneConfig& navigation_lane() const;
  ::apollo::relative_map::NavigationLaneConfig* release_navigation_lane();
  ::apollo::relative_map::NavigationLaneConfig* mutable_navigation_lane();
  void set_allocated_navigation_lane(::apollo::relative_map::NavigationLaneConfig* navigation_lane);

  // @@protoc_insertion_point(class_scope:apollo.relative_map.RelativeMapConfig)
 private:
  void set_has_map_param();
  void clear_has_map_param();
  void set_has_navigation_lane();
  void clear_has_navigation_lane();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::apollo::relative_map::MapGenerationParam* map_param_;
  ::apollo::relative_map::NavigationLaneConfig* navigation_lane_;
  friend struct ::protobuf_modules_2fmap_2frelative_5fmap_2fproto_2frelative_5fmap_5fconfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MapGenerationParam

// optional double default_left_width = 1 [default = 1.75];
inline bool MapGenerationParam::has_default_left_width() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MapGenerationParam::set_has_default_left_width() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MapGenerationParam::clear_has_default_left_width() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MapGenerationParam::clear_default_left_width() {
  default_left_width_ = 1.75;
  clear_has_default_left_width();
}
inline double MapGenerationParam::default_left_width() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.MapGenerationParam.default_left_width)
  return default_left_width_;
}
inline void MapGenerationParam::set_default_left_width(double value) {
  set_has_default_left_width();
  default_left_width_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.MapGenerationParam.default_left_width)
}

// optional double default_right_width = 2 [default = 1.75];
inline bool MapGenerationParam::has_default_right_width() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MapGenerationParam::set_has_default_right_width() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MapGenerationParam::clear_has_default_right_width() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MapGenerationParam::clear_default_right_width() {
  default_right_width_ = 1.75;
  clear_has_default_right_width();
}
inline double MapGenerationParam::default_right_width() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.MapGenerationParam.default_right_width)
  return default_right_width_;
}
inline void MapGenerationParam::set_default_right_width(double value) {
  set_has_default_right_width();
  default_right_width_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.MapGenerationParam.default_right_width)
}

// optional double default_speed_limit = 3 [default = 29.0576];
inline bool MapGenerationParam::has_default_speed_limit() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MapGenerationParam::set_has_default_speed_limit() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MapGenerationParam::clear_has_default_speed_limit() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MapGenerationParam::clear_default_speed_limit() {
  default_speed_limit_ = 29.0576;
  clear_has_default_speed_limit();
}
inline double MapGenerationParam::default_speed_limit() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.MapGenerationParam.default_speed_limit)
  return default_speed_limit_;
}
inline void MapGenerationParam::set_default_speed_limit(double value) {
  set_has_default_speed_limit();
  default_speed_limit_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.MapGenerationParam.default_speed_limit)
}

// -------------------------------------------------------------------

// NavigationLaneConfig

// optional double min_lane_marker_quality = 1 [default = 0.5];
inline bool NavigationLaneConfig::has_min_lane_marker_quality() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NavigationLaneConfig::set_has_min_lane_marker_quality() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NavigationLaneConfig::clear_has_min_lane_marker_quality() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NavigationLaneConfig::clear_min_lane_marker_quality() {
  min_lane_marker_quality_ = 0.5;
  clear_has_min_lane_marker_quality();
}
inline double NavigationLaneConfig::min_lane_marker_quality() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.NavigationLaneConfig.min_lane_marker_quality)
  return min_lane_marker_quality_;
}
inline void NavigationLaneConfig::set_min_lane_marker_quality(double value) {
  set_has_min_lane_marker_quality();
  min_lane_marker_quality_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.NavigationLaneConfig.min_lane_marker_quality)
}

// optional .apollo.relative_map.NavigationLaneConfig.LaneSource lane_source = 2;
inline bool NavigationLaneConfig::has_lane_source() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NavigationLaneConfig::set_has_lane_source() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NavigationLaneConfig::clear_has_lane_source() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NavigationLaneConfig::clear_lane_source() {
  lane_source_ = 1;
  clear_has_lane_source();
}
inline ::apollo::relative_map::NavigationLaneConfig_LaneSource NavigationLaneConfig::lane_source() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.NavigationLaneConfig.lane_source)
  return static_cast< ::apollo::relative_map::NavigationLaneConfig_LaneSource >(lane_source_);
}
inline void NavigationLaneConfig::set_lane_source(::apollo::relative_map::NavigationLaneConfig_LaneSource value) {
  assert(::apollo::relative_map::NavigationLaneConfig_LaneSource_IsValid(value));
  set_has_lane_source();
  lane_source_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.NavigationLaneConfig.lane_source)
}

// optional double max_len_from_navigation_line = 3 [default = 250];
inline bool NavigationLaneConfig::has_max_len_from_navigation_line() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NavigationLaneConfig::set_has_max_len_from_navigation_line() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NavigationLaneConfig::clear_has_max_len_from_navigation_line() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NavigationLaneConfig::clear_max_len_from_navigation_line() {
  max_len_from_navigation_line_ = 250;
  clear_has_max_len_from_navigation_line();
}
inline double NavigationLaneConfig::max_len_from_navigation_line() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.NavigationLaneConfig.max_len_from_navigation_line)
  return max_len_from_navigation_line_;
}
inline void NavigationLaneConfig::set_max_len_from_navigation_line(double value) {
  set_has_max_len_from_navigation_line();
  max_len_from_navigation_line_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.NavigationLaneConfig.max_len_from_navigation_line)
}

// optional double min_len_for_navigation_lane = 4 [default = 150];
inline bool NavigationLaneConfig::has_min_len_for_navigation_lane() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NavigationLaneConfig::set_has_min_len_for_navigation_lane() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NavigationLaneConfig::clear_has_min_len_for_navigation_lane() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NavigationLaneConfig::clear_min_len_for_navigation_lane() {
  min_len_for_navigation_lane_ = 150;
  clear_has_min_len_for_navigation_lane();
}
inline double NavigationLaneConfig::min_len_for_navigation_lane() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.NavigationLaneConfig.min_len_for_navigation_lane)
  return min_len_for_navigation_lane_;
}
inline void NavigationLaneConfig::set_min_len_for_navigation_lane(double value) {
  set_has_min_len_for_navigation_lane();
  min_len_for_navigation_lane_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.NavigationLaneConfig.min_len_for_navigation_lane)
}

// optional double max_len_for_navigation_lane = 5 [default = 250];
inline bool NavigationLaneConfig::has_max_len_for_navigation_lane() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void NavigationLaneConfig::set_has_max_len_for_navigation_lane() {
  _has_bits_[0] |= 0x00000010u;
}
inline void NavigationLaneConfig::clear_has_max_len_for_navigation_lane() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void NavigationLaneConfig::clear_max_len_for_navigation_lane() {
  max_len_for_navigation_lane_ = 250;
  clear_has_max_len_for_navigation_lane();
}
inline double NavigationLaneConfig::max_len_for_navigation_lane() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.NavigationLaneConfig.max_len_for_navigation_lane)
  return max_len_for_navigation_lane_;
}
inline void NavigationLaneConfig::set_max_len_for_navigation_lane(double value) {
  set_has_max_len_for_navigation_lane();
  max_len_for_navigation_lane_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.NavigationLaneConfig.max_len_for_navigation_lane)
}

// optional double ratio_navigation_lane_len_to_speed = 6 [default = 8];
inline bool NavigationLaneConfig::has_ratio_navigation_lane_len_to_speed() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void NavigationLaneConfig::set_has_ratio_navigation_lane_len_to_speed() {
  _has_bits_[0] |= 0x00000020u;
}
inline void NavigationLaneConfig::clear_has_ratio_navigation_lane_len_to_speed() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void NavigationLaneConfig::clear_ratio_navigation_lane_len_to_speed() {
  ratio_navigation_lane_len_to_speed_ = 8;
  clear_has_ratio_navigation_lane_len_to_speed();
}
inline double NavigationLaneConfig::ratio_navigation_lane_len_to_speed() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.NavigationLaneConfig.ratio_navigation_lane_len_to_speed)
  return ratio_navigation_lane_len_to_speed_;
}
inline void NavigationLaneConfig::set_ratio_navigation_lane_len_to_speed(double value) {
  set_has_ratio_navigation_lane_len_to_speed();
  ratio_navigation_lane_len_to_speed_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.NavigationLaneConfig.ratio_navigation_lane_len_to_speed)
}

// optional double max_distance_to_navigation_line = 7 [default = 15];
inline bool NavigationLaneConfig::has_max_distance_to_navigation_line() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void NavigationLaneConfig::set_has_max_distance_to_navigation_line() {
  _has_bits_[0] |= 0x00000040u;
}
inline void NavigationLaneConfig::clear_has_max_distance_to_navigation_line() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void NavigationLaneConfig::clear_max_distance_to_navigation_line() {
  max_distance_to_navigation_line_ = 15;
  clear_has_max_distance_to_navigation_line();
}
inline double NavigationLaneConfig::max_distance_to_navigation_line() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.NavigationLaneConfig.max_distance_to_navigation_line)
  return max_distance_to_navigation_line_;
}
inline void NavigationLaneConfig::set_max_distance_to_navigation_line(double value) {
  set_has_max_distance_to_navigation_line();
  max_distance_to_navigation_line_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.NavigationLaneConfig.max_distance_to_navigation_line)
}

// optional double min_view_range_to_use_lane_marker = 8 [default = 0.5];
inline bool NavigationLaneConfig::has_min_view_range_to_use_lane_marker() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void NavigationLaneConfig::set_has_min_view_range_to_use_lane_marker() {
  _has_bits_[0] |= 0x00000080u;
}
inline void NavigationLaneConfig::clear_has_min_view_range_to_use_lane_marker() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void NavigationLaneConfig::clear_min_view_range_to_use_lane_marker() {
  min_view_range_to_use_lane_marker_ = 0.5;
  clear_has_min_view_range_to_use_lane_marker();
}
inline double NavigationLaneConfig::min_view_range_to_use_lane_marker() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.NavigationLaneConfig.min_view_range_to_use_lane_marker)
  return min_view_range_to_use_lane_marker_;
}
inline void NavigationLaneConfig::set_min_view_range_to_use_lane_marker(double value) {
  set_has_min_view_range_to_use_lane_marker();
  min_view_range_to_use_lane_marker_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.NavigationLaneConfig.min_view_range_to_use_lane_marker)
}

// optional double min_lane_half_width = 9 [default = 1.5];
inline bool NavigationLaneConfig::has_min_lane_half_width() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void NavigationLaneConfig::set_has_min_lane_half_width() {
  _has_bits_[0] |= 0x00000100u;
}
inline void NavigationLaneConfig::clear_has_min_lane_half_width() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void NavigationLaneConfig::clear_min_lane_half_width() {
  min_lane_half_width_ = 1.5;
  clear_has_min_lane_half_width();
}
inline double NavigationLaneConfig::min_lane_half_width() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.NavigationLaneConfig.min_lane_half_width)
  return min_lane_half_width_;
}
inline void NavigationLaneConfig::set_min_lane_half_width(double value) {
  set_has_min_lane_half_width();
  min_lane_half_width_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.NavigationLaneConfig.min_lane_half_width)
}

// optional double max_lane_half_width = 10 [default = 2];
inline bool NavigationLaneConfig::has_max_lane_half_width() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void NavigationLaneConfig::set_has_max_lane_half_width() {
  _has_bits_[0] |= 0x00000200u;
}
inline void NavigationLaneConfig::clear_has_max_lane_half_width() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void NavigationLaneConfig::clear_max_lane_half_width() {
  max_lane_half_width_ = 2;
  clear_has_max_lane_half_width();
}
inline double NavigationLaneConfig::max_lane_half_width() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.NavigationLaneConfig.max_lane_half_width)
  return max_lane_half_width_;
}
inline void NavigationLaneConfig::set_max_lane_half_width(double value) {
  set_has_max_lane_half_width();
  max_lane_half_width_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.NavigationLaneConfig.max_lane_half_width)
}

// optional double lane_marker_weight = 11 [default = 0.1];
inline bool NavigationLaneConfig::has_lane_marker_weight() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void NavigationLaneConfig::set_has_lane_marker_weight() {
  _has_bits_[0] |= 0x00000400u;
}
inline void NavigationLaneConfig::clear_has_lane_marker_weight() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void NavigationLaneConfig::clear_lane_marker_weight() {
  lane_marker_weight_ = 0.1;
  clear_has_lane_marker_weight();
}
inline double NavigationLaneConfig::lane_marker_weight() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.NavigationLaneConfig.lane_marker_weight)
  return lane_marker_weight_;
}
inline void NavigationLaneConfig::set_lane_marker_weight(double value) {
  set_has_lane_marker_weight();
  lane_marker_weight_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.NavigationLaneConfig.lane_marker_weight)
}

// -------------------------------------------------------------------

// RelativeMapConfig

// optional .apollo.relative_map.MapGenerationParam map_param = 1;
inline bool RelativeMapConfig::has_map_param() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RelativeMapConfig::set_has_map_param() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RelativeMapConfig::clear_has_map_param() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RelativeMapConfig::clear_map_param() {
  if (map_param_ != NULL) map_param_->Clear();
  clear_has_map_param();
}
inline const ::apollo::relative_map::MapGenerationParam& RelativeMapConfig::_internal_map_param() const {
  return *map_param_;
}
inline const ::apollo::relative_map::MapGenerationParam& RelativeMapConfig::map_param() const {
  const ::apollo::relative_map::MapGenerationParam* p = map_param_;
  // @@protoc_insertion_point(field_get:apollo.relative_map.RelativeMapConfig.map_param)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::relative_map::MapGenerationParam*>(
      &::apollo::relative_map::_MapGenerationParam_default_instance_);
}
inline ::apollo::relative_map::MapGenerationParam* RelativeMapConfig::release_map_param() {
  // @@protoc_insertion_point(field_release:apollo.relative_map.RelativeMapConfig.map_param)
  clear_has_map_param();
  ::apollo::relative_map::MapGenerationParam* temp = map_param_;
  map_param_ = NULL;
  return temp;
}
inline ::apollo::relative_map::MapGenerationParam* RelativeMapConfig::mutable_map_param() {
  set_has_map_param();
  if (map_param_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::relative_map::MapGenerationParam>(GetArenaNoVirtual());
    map_param_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.relative_map.RelativeMapConfig.map_param)
  return map_param_;
}
inline void RelativeMapConfig::set_allocated_map_param(::apollo::relative_map::MapGenerationParam* map_param) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete map_param_;
  }
  if (map_param) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      map_param = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, map_param, submessage_arena);
    }
    set_has_map_param();
  } else {
    clear_has_map_param();
  }
  map_param_ = map_param;
  // @@protoc_insertion_point(field_set_allocated:apollo.relative_map.RelativeMapConfig.map_param)
}

// optional .apollo.relative_map.NavigationLaneConfig navigation_lane = 2;
inline bool RelativeMapConfig::has_navigation_lane() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RelativeMapConfig::set_has_navigation_lane() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RelativeMapConfig::clear_has_navigation_lane() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RelativeMapConfig::clear_navigation_lane() {
  if (navigation_lane_ != NULL) navigation_lane_->Clear();
  clear_has_navigation_lane();
}
inline const ::apollo::relative_map::NavigationLaneConfig& RelativeMapConfig::_internal_navigation_lane() const {
  return *navigation_lane_;
}
inline const ::apollo::relative_map::NavigationLaneConfig& RelativeMapConfig::navigation_lane() const {
  const ::apollo::relative_map::NavigationLaneConfig* p = navigation_lane_;
  // @@protoc_insertion_point(field_get:apollo.relative_map.RelativeMapConfig.navigation_lane)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::relative_map::NavigationLaneConfig*>(
      &::apollo::relative_map::_NavigationLaneConfig_default_instance_);
}
inline ::apollo::relative_map::NavigationLaneConfig* RelativeMapConfig::release_navigation_lane() {
  // @@protoc_insertion_point(field_release:apollo.relative_map.RelativeMapConfig.navigation_lane)
  clear_has_navigation_lane();
  ::apollo::relative_map::NavigationLaneConfig* temp = navigation_lane_;
  navigation_lane_ = NULL;
  return temp;
}
inline ::apollo::relative_map::NavigationLaneConfig* RelativeMapConfig::mutable_navigation_lane() {
  set_has_navigation_lane();
  if (navigation_lane_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::relative_map::NavigationLaneConfig>(GetArenaNoVirtual());
    navigation_lane_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.relative_map.RelativeMapConfig.navigation_lane)
  return navigation_lane_;
}
inline void RelativeMapConfig::set_allocated_navigation_lane(::apollo::relative_map::NavigationLaneConfig* navigation_lane) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete navigation_lane_;
  }
  if (navigation_lane) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      navigation_lane = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, navigation_lane, submessage_arena);
    }
    set_has_navigation_lane();
  } else {
    clear_has_navigation_lane();
  }
  navigation_lane_ = navigation_lane;
  // @@protoc_insertion_point(field_set_allocated:apollo.relative_map.RelativeMapConfig.navigation_lane)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace relative_map
}  // namespace apollo

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::relative_map::NavigationLaneConfig_LaneSource> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::relative_map::NavigationLaneConfig_LaneSource>() {
  return ::apollo::relative_map::NavigationLaneConfig_LaneSource_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_modules_2fmap_2frelative_5fmap_2fproto_2frelative_5fmap_5fconfig_2eproto
