// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/perception/proto/perception_ultrasonic.proto

#ifndef PROTOBUF_INCLUDED_modules_2fperception_2fproto_2fperception_5fultrasonic_2eproto
#define PROTOBUF_INCLUDED_modules_2fperception_2fproto_2fperception_5fultrasonic_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "modules/common/proto/header.pb.h"
#include "modules/common/proto/geometry.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fperception_2fproto_2fperception_5fultrasonic_2eproto 

namespace protobuf_modules_2fperception_2fproto_2fperception_5fultrasonic_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_modules_2fperception_2fproto_2fperception_5fultrasonic_2eproto
namespace apollo {
namespace perception {
class ImpendingCollisionEdge;
class ImpendingCollisionEdgeDefaultTypeInternal;
extern ImpendingCollisionEdgeDefaultTypeInternal _ImpendingCollisionEdge_default_instance_;
class ImpendingCollisionEdges;
class ImpendingCollisionEdgesDefaultTypeInternal;
extern ImpendingCollisionEdgesDefaultTypeInternal _ImpendingCollisionEdges_default_instance_;
}  // namespace perception
}  // namespace apollo
namespace google {
namespace protobuf {
template<> ::apollo::perception::ImpendingCollisionEdge* Arena::CreateMaybeMessage<::apollo::perception::ImpendingCollisionEdge>(Arena*);
template<> ::apollo::perception::ImpendingCollisionEdges* Arena::CreateMaybeMessage<::apollo::perception::ImpendingCollisionEdges>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace apollo {
namespace perception {

// ===================================================================

class ImpendingCollisionEdge : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.perception.ImpendingCollisionEdge) */ {
 public:
  ImpendingCollisionEdge();
  virtual ~ImpendingCollisionEdge();

  ImpendingCollisionEdge(const ImpendingCollisionEdge& from);

  inline ImpendingCollisionEdge& operator=(const ImpendingCollisionEdge& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ImpendingCollisionEdge(ImpendingCollisionEdge&& from) noexcept
    : ImpendingCollisionEdge() {
    *this = ::std::move(from);
  }

  inline ImpendingCollisionEdge& operator=(ImpendingCollisionEdge&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ImpendingCollisionEdge& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ImpendingCollisionEdge* internal_default_instance() {
    return reinterpret_cast<const ImpendingCollisionEdge*>(
               &_ImpendingCollisionEdge_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ImpendingCollisionEdge* other);
  friend void swap(ImpendingCollisionEdge& a, ImpendingCollisionEdge& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ImpendingCollisionEdge* New() const final {
    return CreateMaybeMessage<ImpendingCollisionEdge>(NULL);
  }

  ImpendingCollisionEdge* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ImpendingCollisionEdge>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ImpendingCollisionEdge& from);
  void MergeFrom(const ImpendingCollisionEdge& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImpendingCollisionEdge* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 cone_id_list = 2 [deprecated = true];
  GOOGLE_PROTOBUF_DEPRECATED_ATTR int cone_id_list_size() const;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR void clear_cone_id_list();
  GOOGLE_PROTOBUF_DEPRECATED_ATTR static const int kConeIdListFieldNumber = 2;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR ::google::protobuf::int32 cone_id_list(int index) const;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR void set_cone_id_list(int index, ::google::protobuf::int32 value);
  GOOGLE_PROTOBUF_DEPRECATED_ATTR void add_cone_id_list(::google::protobuf::int32 value);
  GOOGLE_PROTOBUF_DEPRECATED_ATTR const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      cone_id_list() const;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_cone_id_list();

  // repeated .apollo.common.Point3D point = 3;
  int point_size() const;
  void clear_point();
  static const int kPointFieldNumber = 3;
  ::apollo::common::Point3D* mutable_point(int index);
  ::google::protobuf::RepeatedPtrField< ::apollo::common::Point3D >*
      mutable_point();
  const ::apollo::common::Point3D& point(int index) const;
  ::apollo::common::Point3D* add_point();
  const ::google::protobuf::RepeatedPtrField< ::apollo::common::Point3D >&
      point() const;

  // optional double tracking_time = 4;
  bool has_tracking_time() const;
  void clear_tracking_time();
  static const int kTrackingTimeFieldNumber = 4;
  double tracking_time() const;
  void set_tracking_time(double value);

  // optional int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:apollo.perception.ImpendingCollisionEdge)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_tracking_time();
  void clear_has_tracking_time();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > cone_id_list_;
  ::google::protobuf::RepeatedPtrField< ::apollo::common::Point3D > point_;
  double tracking_time_;
  ::google::protobuf::int32 id_;
  friend struct ::protobuf_modules_2fperception_2fproto_2fperception_5fultrasonic_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ImpendingCollisionEdges : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.perception.ImpendingCollisionEdges) */ {
 public:
  ImpendingCollisionEdges();
  virtual ~ImpendingCollisionEdges();

  ImpendingCollisionEdges(const ImpendingCollisionEdges& from);

  inline ImpendingCollisionEdges& operator=(const ImpendingCollisionEdges& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ImpendingCollisionEdges(ImpendingCollisionEdges&& from) noexcept
    : ImpendingCollisionEdges() {
    *this = ::std::move(from);
  }

  inline ImpendingCollisionEdges& operator=(ImpendingCollisionEdges&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ImpendingCollisionEdges& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ImpendingCollisionEdges* internal_default_instance() {
    return reinterpret_cast<const ImpendingCollisionEdges*>(
               &_ImpendingCollisionEdges_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ImpendingCollisionEdges* other);
  friend void swap(ImpendingCollisionEdges& a, ImpendingCollisionEdges& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ImpendingCollisionEdges* New() const final {
    return CreateMaybeMessage<ImpendingCollisionEdges>(NULL);
  }

  ImpendingCollisionEdges* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ImpendingCollisionEdges>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ImpendingCollisionEdges& from);
  void MergeFrom(const ImpendingCollisionEdges& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImpendingCollisionEdges* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.perception.ImpendingCollisionEdge impending_collision_edge = 1;
  int impending_collision_edge_size() const;
  void clear_impending_collision_edge();
  static const int kImpendingCollisionEdgeFieldNumber = 1;
  ::apollo::perception::ImpendingCollisionEdge* mutable_impending_collision_edge(int index);
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::ImpendingCollisionEdge >*
      mutable_impending_collision_edge();
  const ::apollo::perception::ImpendingCollisionEdge& impending_collision_edge(int index) const;
  ::apollo::perception::ImpendingCollisionEdge* add_impending_collision_edge();
  const ::google::protobuf::RepeatedPtrField< ::apollo::perception::ImpendingCollisionEdge >&
      impending_collision_edge() const;

  // optional .apollo.common.Header header = 2;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 2;
  private:
  const ::apollo::common::Header& _internal_header() const;
  public:
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* release_header();
  ::apollo::common::Header* mutable_header();
  void set_allocated_header(::apollo::common::Header* header);

  // @@protoc_insertion_point(class_scope:apollo.perception.ImpendingCollisionEdges)
 private:
  void set_has_header();
  void clear_has_header();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::ImpendingCollisionEdge > impending_collision_edge_;
  ::apollo::common::Header* header_;
  friend struct ::protobuf_modules_2fperception_2fproto_2fperception_5fultrasonic_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ImpendingCollisionEdge

// optional int32 id = 1;
inline bool ImpendingCollisionEdge::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ImpendingCollisionEdge::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ImpendingCollisionEdge::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ImpendingCollisionEdge::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 ImpendingCollisionEdge::id() const {
  // @@protoc_insertion_point(field_get:apollo.perception.ImpendingCollisionEdge.id)
  return id_;
}
inline void ImpendingCollisionEdge::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.ImpendingCollisionEdge.id)
}

// repeated int32 cone_id_list = 2 [deprecated = true];
inline int ImpendingCollisionEdge::cone_id_list_size() const {
  return cone_id_list_.size();
}
inline void ImpendingCollisionEdge::clear_cone_id_list() {
  cone_id_list_.Clear();
}
inline ::google::protobuf::int32 ImpendingCollisionEdge::cone_id_list(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.ImpendingCollisionEdge.cone_id_list)
  return cone_id_list_.Get(index);
}
inline void ImpendingCollisionEdge::set_cone_id_list(int index, ::google::protobuf::int32 value) {
  cone_id_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:apollo.perception.ImpendingCollisionEdge.cone_id_list)
}
inline void ImpendingCollisionEdge::add_cone_id_list(::google::protobuf::int32 value) {
  cone_id_list_.Add(value);
  // @@protoc_insertion_point(field_add:apollo.perception.ImpendingCollisionEdge.cone_id_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ImpendingCollisionEdge::cone_id_list() const {
  // @@protoc_insertion_point(field_list:apollo.perception.ImpendingCollisionEdge.cone_id_list)
  return cone_id_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ImpendingCollisionEdge::mutable_cone_id_list() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.ImpendingCollisionEdge.cone_id_list)
  return &cone_id_list_;
}

// repeated .apollo.common.Point3D point = 3;
inline int ImpendingCollisionEdge::point_size() const {
  return point_.size();
}
inline ::apollo::common::Point3D* ImpendingCollisionEdge::mutable_point(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.perception.ImpendingCollisionEdge.point)
  return point_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::common::Point3D >*
ImpendingCollisionEdge::mutable_point() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.ImpendingCollisionEdge.point)
  return &point_;
}
inline const ::apollo::common::Point3D& ImpendingCollisionEdge::point(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.ImpendingCollisionEdge.point)
  return point_.Get(index);
}
inline ::apollo::common::Point3D* ImpendingCollisionEdge::add_point() {
  // @@protoc_insertion_point(field_add:apollo.perception.ImpendingCollisionEdge.point)
  return point_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::common::Point3D >&
ImpendingCollisionEdge::point() const {
  // @@protoc_insertion_point(field_list:apollo.perception.ImpendingCollisionEdge.point)
  return point_;
}

// optional double tracking_time = 4;
inline bool ImpendingCollisionEdge::has_tracking_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ImpendingCollisionEdge::set_has_tracking_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ImpendingCollisionEdge::clear_has_tracking_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ImpendingCollisionEdge::clear_tracking_time() {
  tracking_time_ = 0;
  clear_has_tracking_time();
}
inline double ImpendingCollisionEdge::tracking_time() const {
  // @@protoc_insertion_point(field_get:apollo.perception.ImpendingCollisionEdge.tracking_time)
  return tracking_time_;
}
inline void ImpendingCollisionEdge::set_tracking_time(double value) {
  set_has_tracking_time();
  tracking_time_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.ImpendingCollisionEdge.tracking_time)
}

// -------------------------------------------------------------------

// ImpendingCollisionEdges

// repeated .apollo.perception.ImpendingCollisionEdge impending_collision_edge = 1;
inline int ImpendingCollisionEdges::impending_collision_edge_size() const {
  return impending_collision_edge_.size();
}
inline void ImpendingCollisionEdges::clear_impending_collision_edge() {
  impending_collision_edge_.Clear();
}
inline ::apollo::perception::ImpendingCollisionEdge* ImpendingCollisionEdges::mutable_impending_collision_edge(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.perception.ImpendingCollisionEdges.impending_collision_edge)
  return impending_collision_edge_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::ImpendingCollisionEdge >*
ImpendingCollisionEdges::mutable_impending_collision_edge() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.ImpendingCollisionEdges.impending_collision_edge)
  return &impending_collision_edge_;
}
inline const ::apollo::perception::ImpendingCollisionEdge& ImpendingCollisionEdges::impending_collision_edge(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.ImpendingCollisionEdges.impending_collision_edge)
  return impending_collision_edge_.Get(index);
}
inline ::apollo::perception::ImpendingCollisionEdge* ImpendingCollisionEdges::add_impending_collision_edge() {
  // @@protoc_insertion_point(field_add:apollo.perception.ImpendingCollisionEdges.impending_collision_edge)
  return impending_collision_edge_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::ImpendingCollisionEdge >&
ImpendingCollisionEdges::impending_collision_edge() const {
  // @@protoc_insertion_point(field_list:apollo.perception.ImpendingCollisionEdges.impending_collision_edge)
  return impending_collision_edge_;
}

// optional .apollo.common.Header header = 2;
inline bool ImpendingCollisionEdges::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ImpendingCollisionEdges::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ImpendingCollisionEdges::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::apollo::common::Header& ImpendingCollisionEdges::_internal_header() const {
  return *header_;
}
inline const ::apollo::common::Header& ImpendingCollisionEdges::header() const {
  const ::apollo::common::Header* p = header_;
  // @@protoc_insertion_point(field_get:apollo.perception.ImpendingCollisionEdges.header)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::common::Header*>(
      &::apollo::common::_Header_default_instance_);
}
inline ::apollo::common::Header* ImpendingCollisionEdges::release_header() {
  // @@protoc_insertion_point(field_release:apollo.perception.ImpendingCollisionEdges.header)
  clear_has_header();
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::apollo::common::Header* ImpendingCollisionEdges::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::common::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.perception.ImpendingCollisionEdges.header)
  return header_;
}
inline void ImpendingCollisionEdges::set_allocated_header(::apollo::common::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    set_has_header();
  } else {
    clear_has_header();
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.ImpendingCollisionEdges.header)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace perception
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_modules_2fperception_2fproto_2fperception_5fultrasonic_2eproto
