// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/perception/proto/sensor_meta_schema.proto

#include "modules/perception/proto/sensor_meta_schema.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_SensorMeta;
}  // namespace protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto
namespace apollo {
namespace perception {
class SensorMetaDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SensorMeta>
      _instance;
} _SensorMeta_default_instance_;
class MultiSensorMetaDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MultiSensorMeta>
      _instance;
} _MultiSensorMeta_default_instance_;
}  // namespace perception
}  // namespace apollo
namespace protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto {
static void InitDefaultsSensorMeta() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::perception::_SensorMeta_default_instance_;
    new (ptr) ::apollo::perception::SensorMeta();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::perception::SensorMeta::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SensorMeta =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSensorMeta}, {}};

static void InitDefaultsMultiSensorMeta() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::perception::_MultiSensorMeta_default_instance_;
    new (ptr) ::apollo::perception::MultiSensorMeta();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::perception::MultiSensorMeta::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_MultiSensorMeta =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsMultiSensorMeta}, {
      &protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::scc_info_SensorMeta.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SensorMeta.base);
  ::google::protobuf::internal::InitSCC(&scc_info_MultiSensorMeta.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::perception::SensorMeta, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::perception::SensorMeta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::perception::SensorMeta, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::perception::SensorMeta, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::perception::SensorMeta, orientation_),
  0,
  2,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::perception::MultiSensorMeta, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::perception::MultiSensorMeta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::perception::MultiSensorMeta, sensor_meta_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::apollo::perception::SensorMeta)},
  { 11, 17, sizeof(::apollo::perception::MultiSensorMeta)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::perception::_SensorMeta_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::perception::_MultiSensorMeta_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "modules/perception/proto/sensor_meta_schema.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n1modules/perception/proto/sensor_meta_s"
      "chema.proto\022\021apollo.perception\"\255\004\n\nSenso"
      "rMeta\022\014\n\004name\030\001 \001(\t\0226\n\004type\030\002 \001(\0162(.apol"
      "lo.perception.SensorMeta.SensorType\022D\n\013o"
      "rientation\030\003 \001(\0162/.apollo.perception.Sen"
      "sorMeta.SensorOrientation\"\367\001\n\nSensorType"
      "\022 \n\023UNKNOWN_SENSOR_TYPE\020\377\377\377\377\377\377\377\377\377\001\022\017\n\013VE"
      "LODYNE_64\020\000\022\017\n\013VELODYNE_32\020\001\022\017\n\013VELODYNE"
      "_16\020\002\022\r\n\tLDLIDAR_4\020\003\022\r\n\tLDLIDAR_1\020\004\022\025\n\021S"
      "HORT_RANGE_RADAR\020\005\022\024\n\020LONG_RANGE_RADAR\020\006"
      "\022\024\n\020MONOCULAR_CAMERA\020\007\022\021\n\rSTEREO_CAMERA\020"
      "\010\022\016\n\nULTRASONIC\020\t\022\020\n\014VELODYNE_128\020\n\"\230\001\n\021"
      "SensorOrientation\022\t\n\005FRONT\020\000\022\020\n\014LEFT_FOR"
      "WARD\020\001\022\010\n\004LEFT\020\002\022\021\n\rLEFT_BACKWARD\020\003\022\010\n\004R"
      "EAR\020\004\022\022\n\016RIGHT_BACKWARD\020\005\022\t\n\005RIGHT\020\006\022\021\n\r"
      "RIGHT_FORWARD\020\007\022\r\n\tPANORAMIC\020\010\"E\n\017MultiS"
      "ensorMeta\0222\n\013sensor_meta\030\001 \003(\0132\035.apollo."
      "perception.SensorMeta"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 701);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "modules/perception/proto/sensor_meta_schema.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto
namespace apollo {
namespace perception {
const ::google::protobuf::EnumDescriptor* SensorMeta_SensorType_descriptor() {
  protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::file_level_enum_descriptors[0];
}
bool SensorMeta_SensorType_IsValid(int value) {
  switch (value) {
    case -1:
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const SensorMeta_SensorType SensorMeta::UNKNOWN_SENSOR_TYPE;
const SensorMeta_SensorType SensorMeta::VELODYNE_64;
const SensorMeta_SensorType SensorMeta::VELODYNE_32;
const SensorMeta_SensorType SensorMeta::VELODYNE_16;
const SensorMeta_SensorType SensorMeta::LDLIDAR_4;
const SensorMeta_SensorType SensorMeta::LDLIDAR_1;
const SensorMeta_SensorType SensorMeta::SHORT_RANGE_RADAR;
const SensorMeta_SensorType SensorMeta::LONG_RANGE_RADAR;
const SensorMeta_SensorType SensorMeta::MONOCULAR_CAMERA;
const SensorMeta_SensorType SensorMeta::STEREO_CAMERA;
const SensorMeta_SensorType SensorMeta::ULTRASONIC;
const SensorMeta_SensorType SensorMeta::VELODYNE_128;
const SensorMeta_SensorType SensorMeta::SensorType_MIN;
const SensorMeta_SensorType SensorMeta::SensorType_MAX;
const int SensorMeta::SensorType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* SensorMeta_SensorOrientation_descriptor() {
  protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::file_level_enum_descriptors[1];
}
bool SensorMeta_SensorOrientation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const SensorMeta_SensorOrientation SensorMeta::FRONT;
const SensorMeta_SensorOrientation SensorMeta::LEFT_FORWARD;
const SensorMeta_SensorOrientation SensorMeta::LEFT;
const SensorMeta_SensorOrientation SensorMeta::LEFT_BACKWARD;
const SensorMeta_SensorOrientation SensorMeta::REAR;
const SensorMeta_SensorOrientation SensorMeta::RIGHT_BACKWARD;
const SensorMeta_SensorOrientation SensorMeta::RIGHT;
const SensorMeta_SensorOrientation SensorMeta::RIGHT_FORWARD;
const SensorMeta_SensorOrientation SensorMeta::PANORAMIC;
const SensorMeta_SensorOrientation SensorMeta::SensorOrientation_MIN;
const SensorMeta_SensorOrientation SensorMeta::SensorOrientation_MAX;
const int SensorMeta::SensorOrientation_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void SensorMeta::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SensorMeta::kNameFieldNumber;
const int SensorMeta::kTypeFieldNumber;
const int SensorMeta::kOrientationFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SensorMeta::SensorMeta()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::scc_info_SensorMeta.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.perception.SensorMeta)
}
SensorMeta::SensorMeta(const SensorMeta& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  ::memcpy(&orientation_, &from.orientation_,
    static_cast<size_t>(reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&orientation_)) + sizeof(type_));
  // @@protoc_insertion_point(copy_constructor:apollo.perception.SensorMeta)
}

void SensorMeta::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  orientation_ = 0;
  type_ = -1;
}

SensorMeta::~SensorMeta() {
  // @@protoc_insertion_point(destructor:apollo.perception.SensorMeta)
  SharedDtor();
}

void SensorMeta::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SensorMeta::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SensorMeta::descriptor() {
  ::protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SensorMeta& SensorMeta::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::scc_info_SensorMeta.base);
  return *internal_default_instance();
}


void SensorMeta::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.perception.SensorMeta)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    name_.ClearNonDefaultToEmptyNoArena();
  }
  if (cached_has_bits & 6u) {
    orientation_ = 0;
    type_ = -1;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SensorMeta::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.perception.SensorMeta)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.perception.SensorMeta.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.perception.SensorMeta.SensorType type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::apollo::perception::SensorMeta_SensorType_IsValid(value)) {
            set_type(static_cast< ::apollo::perception::SensorMeta_SensorType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                2, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.perception.SensorMeta.SensorOrientation orientation = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::apollo::perception::SensorMeta_SensorOrientation_IsValid(value)) {
            set_orientation(static_cast< ::apollo::perception::SensorMeta_SensorOrientation >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                3, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.perception.SensorMeta)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.perception.SensorMeta)
  return false;
#undef DO_
}

void SensorMeta::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.perception.SensorMeta)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.perception.SensorMeta.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional .apollo.perception.SensorMeta.SensorType type = 2;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->type(), output);
  }

  // optional .apollo.perception.SensorMeta.SensorOrientation orientation = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->orientation(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.perception.SensorMeta)
}

::google::protobuf::uint8* SensorMeta::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.perception.SensorMeta)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.perception.SensorMeta.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional .apollo.perception.SensorMeta.SensorType type = 2;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->type(), target);
  }

  // optional .apollo.perception.SensorMeta.SensorOrientation orientation = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->orientation(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.perception.SensorMeta)
  return target;
}

size_t SensorMeta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.perception.SensorMeta)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 7u) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional .apollo.perception.SensorMeta.SensorOrientation orientation = 3;
    if (has_orientation()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->orientation());
    }

    // optional .apollo.perception.SensorMeta.SensorType type = 2;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SensorMeta::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.perception.SensorMeta)
  GOOGLE_DCHECK_NE(&from, this);
  const SensorMeta* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SensorMeta>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.perception.SensorMeta)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.perception.SensorMeta)
    MergeFrom(*source);
  }
}

void SensorMeta::MergeFrom(const SensorMeta& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.perception.SensorMeta)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      orientation_ = from.orientation_;
    }
    if (cached_has_bits & 0x00000004u) {
      type_ = from.type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SensorMeta::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.perception.SensorMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SensorMeta::CopyFrom(const SensorMeta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.perception.SensorMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SensorMeta::IsInitialized() const {
  return true;
}

void SensorMeta::Swap(SensorMeta* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SensorMeta::InternalSwap(SensorMeta* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(orientation_, other->orientation_);
  swap(type_, other->type_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SensorMeta::GetMetadata() const {
  protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MultiSensorMeta::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MultiSensorMeta::kSensorMetaFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MultiSensorMeta::MultiSensorMeta()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::scc_info_MultiSensorMeta.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.perception.MultiSensorMeta)
}
MultiSensorMeta::MultiSensorMeta(const MultiSensorMeta& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      sensor_meta_(from.sensor_meta_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:apollo.perception.MultiSensorMeta)
}

void MultiSensorMeta::SharedCtor() {
}

MultiSensorMeta::~MultiSensorMeta() {
  // @@protoc_insertion_point(destructor:apollo.perception.MultiSensorMeta)
  SharedDtor();
}

void MultiSensorMeta::SharedDtor() {
}

void MultiSensorMeta::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MultiSensorMeta::descriptor() {
  ::protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MultiSensorMeta& MultiSensorMeta::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::scc_info_MultiSensorMeta.base);
  return *internal_default_instance();
}


void MultiSensorMeta::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.perception.MultiSensorMeta)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sensor_meta_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool MultiSensorMeta::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.perception.MultiSensorMeta)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .apollo.perception.SensorMeta sensor_meta = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_sensor_meta()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.perception.MultiSensorMeta)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.perception.MultiSensorMeta)
  return false;
#undef DO_
}

void MultiSensorMeta::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.perception.MultiSensorMeta)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .apollo.perception.SensorMeta sensor_meta = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->sensor_meta_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->sensor_meta(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.perception.MultiSensorMeta)
}

::google::protobuf::uint8* MultiSensorMeta::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.perception.MultiSensorMeta)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .apollo.perception.SensorMeta sensor_meta = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->sensor_meta_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->sensor_meta(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.perception.MultiSensorMeta)
  return target;
}

size_t MultiSensorMeta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.perception.MultiSensorMeta)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .apollo.perception.SensorMeta sensor_meta = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->sensor_meta_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->sensor_meta(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MultiSensorMeta::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.perception.MultiSensorMeta)
  GOOGLE_DCHECK_NE(&from, this);
  const MultiSensorMeta* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MultiSensorMeta>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.perception.MultiSensorMeta)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.perception.MultiSensorMeta)
    MergeFrom(*source);
  }
}

void MultiSensorMeta::MergeFrom(const MultiSensorMeta& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.perception.MultiSensorMeta)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  sensor_meta_.MergeFrom(from.sensor_meta_);
}

void MultiSensorMeta::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.perception.MultiSensorMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MultiSensorMeta::CopyFrom(const MultiSensorMeta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.perception.MultiSensorMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MultiSensorMeta::IsInitialized() const {
  return true;
}

void MultiSensorMeta::Swap(MultiSensorMeta* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MultiSensorMeta::InternalSwap(MultiSensorMeta* other) {
  using std::swap;
  CastToBase(&sensor_meta_)->InternalSwap(CastToBase(&other->sensor_meta_));
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MultiSensorMeta::GetMetadata() const {
  protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fperception_2fproto_2fsensor_5fmeta_5fschema_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace perception
}  // namespace apollo
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::perception::SensorMeta* Arena::CreateMaybeMessage< ::apollo::perception::SensorMeta >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::perception::SensorMeta >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::perception::MultiSensorMeta* Arena::CreateMaybeMessage< ::apollo::perception::MultiSensorMeta >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::perception::MultiSensorMeta >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
