// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/localization/proto/measure.proto

#include "modules/localization/proto/measure.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_modules_2fcommon_2fproto_2fgeometry_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_2fproto_2fgeometry_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Point3D;
}  // namespace protobuf_modules_2fcommon_2fproto_2fgeometry_2eproto
namespace protobuf_modules_2fcommon_2fproto_2fheader_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_2fproto_2fheader_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Header;
}  // namespace protobuf_modules_2fcommon_2fproto_2fheader_2eproto
namespace apollo {
namespace localization {
class IntegMeasureDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<IntegMeasure>
      _instance;
} _IntegMeasure_default_instance_;
}  // namespace localization
}  // namespace apollo
namespace protobuf_modules_2flocalization_2fproto_2fmeasure_2eproto {
static void InitDefaultsIntegMeasure() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::localization::_IntegMeasure_default_instance_;
    new (ptr) ::apollo::localization::IntegMeasure();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::localization::IntegMeasure::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_IntegMeasure =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsIntegMeasure}, {
      &protobuf_modules_2fcommon_2fproto_2fheader_2eproto::scc_info_Header.base,
      &protobuf_modules_2fcommon_2fproto_2fgeometry_2eproto::scc_info_Point3D.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_IntegMeasure.base);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::localization::IntegMeasure, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::localization::IntegMeasure, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::localization::IntegMeasure, header_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::localization::IntegMeasure, measure_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::localization::IntegMeasure, frame_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::localization::IntegMeasure, position_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::localization::IntegMeasure, velocity_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::localization::IntegMeasure, yaw_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::localization::IntegMeasure, zone_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::localization::IntegMeasure, is_have_variance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::localization::IntegMeasure, is_gnss_double_antenna_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::localization::IntegMeasure, measure_covar_),
  0,
  3,
  4,
  1,
  2,
  5,
  6,
  7,
  8,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 15, sizeof(::apollo::localization::IntegMeasure)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::localization::_IntegMeasure_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "modules/localization/proto/measure.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n(modules/localization/proto/measure.pro"
      "to\022\023apollo.localization\032!modules/common/"
      "proto/header.proto\032#modules/common/proto"
      "/geometry.proto\"\326\004\n\014IntegMeasure\022%\n\006head"
      "er\030\001 \001(\0132\025.apollo.common.Header\022C\n\014measu"
      "re_type\030\002 \001(\0162-.apollo.localization.Inte"
      "gMeasure.MeasureType\022\?\n\nframe_type\030\003 \001(\016"
      "2+.apollo.localization.IntegMeasure.Fram"
      "eType\022(\n\010position\030\004 \001(\0132\026.apollo.common."
      "Point3D\022(\n\010velocity\030\005 \001(\0132\026.apollo.commo"
      "n.Point3D\022\013\n\003yaw\030\006 \001(\001\022\017\n\007zone_id\030\007 \001(\005\022"
      "\030\n\020is_have_variance\030\010 \001(\010\022\036\n\026is_gnss_dou"
      "ble_antenna\030\t \001(\010\022\031\n\rmeasure_covar\030\n \003(\001"
      "B\002\020\001\"\232\001\n\013MeasureType\022\021\n\rGNSS_POS_ONLY\020\000\022"
      "\020\n\014GNSS_POS_VEL\020\001\022\017\n\013GNSS_POS_XY\020\002\022\021\n\rGN"
      "SS_VEL_ONLY\020\003\022\023\n\017POINT_CLOUD_POS\020\004\022\025\n\021OD"
      "OMETER_VEL_ONLY\020\005\022\026\n\022VEHICLE_CONSTRAINT\020"
      "\006\"5\n\tFrameType\022\007\n\003ENU\020\000\022\010\n\004ECEF\020\001\022\007\n\003UTM"
      "\020\002\022\014\n\010ODOMETER\020\003"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 736);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "modules/localization/proto/measure.proto", &protobuf_RegisterTypes);
  ::protobuf_modules_2fcommon_2fproto_2fheader_2eproto::AddDescriptors();
  ::protobuf_modules_2fcommon_2fproto_2fgeometry_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_modules_2flocalization_2fproto_2fmeasure_2eproto
namespace apollo {
namespace localization {
const ::google::protobuf::EnumDescriptor* IntegMeasure_MeasureType_descriptor() {
  protobuf_modules_2flocalization_2fproto_2fmeasure_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modules_2flocalization_2fproto_2fmeasure_2eproto::file_level_enum_descriptors[0];
}
bool IntegMeasure_MeasureType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const IntegMeasure_MeasureType IntegMeasure::GNSS_POS_ONLY;
const IntegMeasure_MeasureType IntegMeasure::GNSS_POS_VEL;
const IntegMeasure_MeasureType IntegMeasure::GNSS_POS_XY;
const IntegMeasure_MeasureType IntegMeasure::GNSS_VEL_ONLY;
const IntegMeasure_MeasureType IntegMeasure::POINT_CLOUD_POS;
const IntegMeasure_MeasureType IntegMeasure::ODOMETER_VEL_ONLY;
const IntegMeasure_MeasureType IntegMeasure::VEHICLE_CONSTRAINT;
const IntegMeasure_MeasureType IntegMeasure::MeasureType_MIN;
const IntegMeasure_MeasureType IntegMeasure::MeasureType_MAX;
const int IntegMeasure::MeasureType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* IntegMeasure_FrameType_descriptor() {
  protobuf_modules_2flocalization_2fproto_2fmeasure_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modules_2flocalization_2fproto_2fmeasure_2eproto::file_level_enum_descriptors[1];
}
bool IntegMeasure_FrameType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const IntegMeasure_FrameType IntegMeasure::ENU;
const IntegMeasure_FrameType IntegMeasure::ECEF;
const IntegMeasure_FrameType IntegMeasure::UTM;
const IntegMeasure_FrameType IntegMeasure::ODOMETER;
const IntegMeasure_FrameType IntegMeasure::FrameType_MIN;
const IntegMeasure_FrameType IntegMeasure::FrameType_MAX;
const int IntegMeasure::FrameType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void IntegMeasure::InitAsDefaultInstance() {
  ::apollo::localization::_IntegMeasure_default_instance_._instance.get_mutable()->header_ = const_cast< ::apollo::common::Header*>(
      ::apollo::common::Header::internal_default_instance());
  ::apollo::localization::_IntegMeasure_default_instance_._instance.get_mutable()->position_ = const_cast< ::apollo::common::Point3D*>(
      ::apollo::common::Point3D::internal_default_instance());
  ::apollo::localization::_IntegMeasure_default_instance_._instance.get_mutable()->velocity_ = const_cast< ::apollo::common::Point3D*>(
      ::apollo::common::Point3D::internal_default_instance());
}
void IntegMeasure::clear_header() {
  if (header_ != NULL) header_->Clear();
  clear_has_header();
}
void IntegMeasure::clear_position() {
  if (position_ != NULL) position_->Clear();
  clear_has_position();
}
void IntegMeasure::clear_velocity() {
  if (velocity_ != NULL) velocity_->Clear();
  clear_has_velocity();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int IntegMeasure::kHeaderFieldNumber;
const int IntegMeasure::kMeasureTypeFieldNumber;
const int IntegMeasure::kFrameTypeFieldNumber;
const int IntegMeasure::kPositionFieldNumber;
const int IntegMeasure::kVelocityFieldNumber;
const int IntegMeasure::kYawFieldNumber;
const int IntegMeasure::kZoneIdFieldNumber;
const int IntegMeasure::kIsHaveVarianceFieldNumber;
const int IntegMeasure::kIsGnssDoubleAntennaFieldNumber;
const int IntegMeasure::kMeasureCovarFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

IntegMeasure::IntegMeasure()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_modules_2flocalization_2fproto_2fmeasure_2eproto::scc_info_IntegMeasure.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.localization.IntegMeasure)
}
IntegMeasure::IntegMeasure(const IntegMeasure& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      measure_covar_(from.measure_covar_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_header()) {
    header_ = new ::apollo::common::Header(*from.header_);
  } else {
    header_ = NULL;
  }
  if (from.has_position()) {
    position_ = new ::apollo::common::Point3D(*from.position_);
  } else {
    position_ = NULL;
  }
  if (from.has_velocity()) {
    velocity_ = new ::apollo::common::Point3D(*from.velocity_);
  } else {
    velocity_ = NULL;
  }
  ::memcpy(&measure_type_, &from.measure_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&is_gnss_double_antenna_) -
    reinterpret_cast<char*>(&measure_type_)) + sizeof(is_gnss_double_antenna_));
  // @@protoc_insertion_point(copy_constructor:apollo.localization.IntegMeasure)
}

void IntegMeasure::SharedCtor() {
  ::memset(&header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&is_gnss_double_antenna_) -
      reinterpret_cast<char*>(&header_)) + sizeof(is_gnss_double_antenna_));
}

IntegMeasure::~IntegMeasure() {
  // @@protoc_insertion_point(destructor:apollo.localization.IntegMeasure)
  SharedDtor();
}

void IntegMeasure::SharedDtor() {
  if (this != internal_default_instance()) delete header_;
  if (this != internal_default_instance()) delete position_;
  if (this != internal_default_instance()) delete velocity_;
}

void IntegMeasure::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* IntegMeasure::descriptor() {
  ::protobuf_modules_2flocalization_2fproto_2fmeasure_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2flocalization_2fproto_2fmeasure_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const IntegMeasure& IntegMeasure::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_modules_2flocalization_2fproto_2fmeasure_2eproto::scc_info_IntegMeasure.base);
  return *internal_default_instance();
}


void IntegMeasure::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.localization.IntegMeasure)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  measure_covar_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(header_ != NULL);
      header_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(position_ != NULL);
      position_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(velocity_ != NULL);
      velocity_->Clear();
    }
  }
  if (cached_has_bits & 248u) {
    ::memset(&measure_type_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&is_have_variance_) -
        reinterpret_cast<char*>(&measure_type_)) + sizeof(is_have_variance_));
  }
  is_gnss_double_antenna_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool IntegMeasure::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.localization.IntegMeasure)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .apollo.common.Header header = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.localization.IntegMeasure.MeasureType measure_type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::apollo::localization::IntegMeasure_MeasureType_IsValid(value)) {
            set_measure_type(static_cast< ::apollo::localization::IntegMeasure_MeasureType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                2, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.localization.IntegMeasure.FrameType frame_type = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::apollo::localization::IntegMeasure_FrameType_IsValid(value)) {
            set_frame_type(static_cast< ::apollo::localization::IntegMeasure_FrameType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                3, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.common.Point3D position = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_position()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.common.Point3D velocity = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_velocity()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double yaw = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(49u /* 49 & 0xFF */)) {
          set_has_yaw();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &yaw_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 zone_id = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {
          set_has_zone_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &zone_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool is_have_variance = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {
          set_has_is_have_variance();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_have_variance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool is_gnss_double_antenna = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {
          set_has_is_gnss_double_antenna();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_gnss_double_antenna_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated double measure_covar = 10 [packed = true];
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_measure_covar())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(81u /* 81 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 82u, input, this->mutable_measure_covar())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.localization.IntegMeasure)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.localization.IntegMeasure)
  return false;
#undef DO_
}

void IntegMeasure::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.localization.IntegMeasure)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .apollo.common.Header header = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_header(), output);
  }

  // optional .apollo.localization.IntegMeasure.MeasureType measure_type = 2;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->measure_type(), output);
  }

  // optional .apollo.localization.IntegMeasure.FrameType frame_type = 3;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->frame_type(), output);
  }

  // optional .apollo.common.Point3D position = 4;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_internal_position(), output);
  }

  // optional .apollo.common.Point3D velocity = 5;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->_internal_velocity(), output);
  }

  // optional double yaw = 6;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->yaw(), output);
  }

  // optional int32 zone_id = 7;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->zone_id(), output);
  }

  // optional bool is_have_variance = 8;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->is_have_variance(), output);
  }

  // optional bool is_gnss_double_antenna = 9;
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->is_gnss_double_antenna(), output);
  }

  // repeated double measure_covar = 10 [packed = true];
  if (this->measure_covar_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(10, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _measure_covar_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteDoubleArray(
      this->measure_covar().data(), this->measure_covar_size(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.localization.IntegMeasure)
}

::google::protobuf::uint8* IntegMeasure::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.localization.IntegMeasure)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .apollo.common.Header header = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_header(), deterministic, target);
  }

  // optional .apollo.localization.IntegMeasure.MeasureType measure_type = 2;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->measure_type(), target);
  }

  // optional .apollo.localization.IntegMeasure.FrameType frame_type = 3;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->frame_type(), target);
  }

  // optional .apollo.common.Point3D position = 4;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->_internal_position(), deterministic, target);
  }

  // optional .apollo.common.Point3D velocity = 5;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->_internal_velocity(), deterministic, target);
  }

  // optional double yaw = 6;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->yaw(), target);
  }

  // optional int32 zone_id = 7;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->zone_id(), target);
  }

  // optional bool is_have_variance = 8;
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->is_have_variance(), target);
  }

  // optional bool is_gnss_double_antenna = 9;
  if (cached_has_bits & 0x00000100u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(9, this->is_gnss_double_antenna(), target);
  }

  // repeated double measure_covar = 10 [packed = true];
  if (this->measure_covar_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      10,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _measure_covar_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->measure_covar_, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.localization.IntegMeasure)
  return target;
}

size_t IntegMeasure::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.localization.IntegMeasure)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated double measure_covar = 10 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->measure_covar_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _measure_covar_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  if (_has_bits_[0 / 32] & 255u) {
    // optional .apollo.common.Header header = 1;
    if (has_header()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *header_);
    }

    // optional .apollo.common.Point3D position = 4;
    if (has_position()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *position_);
    }

    // optional .apollo.common.Point3D velocity = 5;
    if (has_velocity()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *velocity_);
    }

    // optional .apollo.localization.IntegMeasure.MeasureType measure_type = 2;
    if (has_measure_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->measure_type());
    }

    // optional .apollo.localization.IntegMeasure.FrameType frame_type = 3;
    if (has_frame_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->frame_type());
    }

    // optional double yaw = 6;
    if (has_yaw()) {
      total_size += 1 + 8;
    }

    // optional int32 zone_id = 7;
    if (has_zone_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->zone_id());
    }

    // optional bool is_have_variance = 8;
    if (has_is_have_variance()) {
      total_size += 1 + 1;
    }

  }
  // optional bool is_gnss_double_antenna = 9;
  if (has_is_gnss_double_antenna()) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void IntegMeasure::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.localization.IntegMeasure)
  GOOGLE_DCHECK_NE(&from, this);
  const IntegMeasure* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const IntegMeasure>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.localization.IntegMeasure)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.localization.IntegMeasure)
    MergeFrom(*source);
  }
}

void IntegMeasure::MergeFrom(const IntegMeasure& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.localization.IntegMeasure)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  measure_covar_.MergeFrom(from.measure_covar_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_header()->::apollo::common::Header::MergeFrom(from.header());
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_position()->::apollo::common::Point3D::MergeFrom(from.position());
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_velocity()->::apollo::common::Point3D::MergeFrom(from.velocity());
    }
    if (cached_has_bits & 0x00000008u) {
      measure_type_ = from.measure_type_;
    }
    if (cached_has_bits & 0x00000010u) {
      frame_type_ = from.frame_type_;
    }
    if (cached_has_bits & 0x00000020u) {
      yaw_ = from.yaw_;
    }
    if (cached_has_bits & 0x00000040u) {
      zone_id_ = from.zone_id_;
    }
    if (cached_has_bits & 0x00000080u) {
      is_have_variance_ = from.is_have_variance_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00000100u) {
    set_is_gnss_double_antenna(from.is_gnss_double_antenna());
  }
}

void IntegMeasure::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.localization.IntegMeasure)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IntegMeasure::CopyFrom(const IntegMeasure& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.localization.IntegMeasure)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IntegMeasure::IsInitialized() const {
  return true;
}

void IntegMeasure::Swap(IntegMeasure* other) {
  if (other == this) return;
  InternalSwap(other);
}
void IntegMeasure::InternalSwap(IntegMeasure* other) {
  using std::swap;
  measure_covar_.InternalSwap(&other->measure_covar_);
  swap(header_, other->header_);
  swap(position_, other->position_);
  swap(velocity_, other->velocity_);
  swap(measure_type_, other->measure_type_);
  swap(frame_type_, other->frame_type_);
  swap(yaw_, other->yaw_);
  swap(zone_id_, other->zone_id_);
  swap(is_have_variance_, other->is_have_variance_);
  swap(is_gnss_double_antenna_, other->is_gnss_double_antenna_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata IntegMeasure::GetMetadata() const {
  protobuf_modules_2flocalization_2fproto_2fmeasure_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2flocalization_2fproto_2fmeasure_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace localization
}  // namespace apollo
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::localization::IntegMeasure* Arena::CreateMaybeMessage< ::apollo::localization::IntegMeasure >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::localization::IntegMeasure >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
