// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/planning/proto/planning_stats.proto

#ifndef PROTOBUF_INCLUDED_modules_2fplanning_2fproto_2fplanning_5fstats_2eproto
#define PROTOBUF_INCLUDED_modules_2fplanning_2fproto_2fplanning_5fstats_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fplanning_2fproto_2fplanning_5fstats_2eproto 

namespace protobuf_modules_2fplanning_2fproto_2fplanning_5fstats_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_modules_2fplanning_2fproto_2fplanning_5fstats_2eproto
namespace apollo {
namespace planning {
class PlanningStats;
class PlanningStatsDefaultTypeInternal;
extern PlanningStatsDefaultTypeInternal _PlanningStats_default_instance_;
class StatsGroup;
class StatsGroupDefaultTypeInternal;
extern StatsGroupDefaultTypeInternal _StatsGroup_default_instance_;
}  // namespace planning
}  // namespace apollo
namespace google {
namespace protobuf {
template<> ::apollo::planning::PlanningStats* Arena::CreateMaybeMessage<::apollo::planning::PlanningStats>(Arena*);
template<> ::apollo::planning::StatsGroup* Arena::CreateMaybeMessage<::apollo::planning::StatsGroup>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace apollo {
namespace planning {

// ===================================================================

class StatsGroup : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.planning.StatsGroup) */ {
 public:
  StatsGroup();
  virtual ~StatsGroup();

  StatsGroup(const StatsGroup& from);

  inline StatsGroup& operator=(const StatsGroup& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StatsGroup(StatsGroup&& from) noexcept
    : StatsGroup() {
    *this = ::std::move(from);
  }

  inline StatsGroup& operator=(StatsGroup&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StatsGroup& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatsGroup* internal_default_instance() {
    return reinterpret_cast<const StatsGroup*>(
               &_StatsGroup_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(StatsGroup* other);
  friend void swap(StatsGroup& a, StatsGroup& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StatsGroup* New() const final {
    return CreateMaybeMessage<StatsGroup>(NULL);
  }

  StatsGroup* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StatsGroup>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StatsGroup& from);
  void MergeFrom(const StatsGroup& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatsGroup* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double max = 1;
  bool has_max() const;
  void clear_max();
  static const int kMaxFieldNumber = 1;
  double max() const;
  void set_max(double value);

  // optional double sum = 3;
  bool has_sum() const;
  void clear_sum();
  static const int kSumFieldNumber = 3;
  double sum() const;
  void set_sum(double value);

  // optional double avg = 4;
  bool has_avg() const;
  void clear_avg();
  static const int kAvgFieldNumber = 4;
  double avg() const;
  void set_avg(double value);

  // optional int32 num = 5;
  bool has_num() const;
  void clear_num();
  static const int kNumFieldNumber = 5;
  ::google::protobuf::int32 num() const;
  void set_num(::google::protobuf::int32 value);

  // optional double min = 2 [default = 10000000000];
  bool has_min() const;
  void clear_min();
  static const int kMinFieldNumber = 2;
  double min() const;
  void set_min(double value);

  // @@protoc_insertion_point(class_scope:apollo.planning.StatsGroup)
 private:
  void set_has_max();
  void clear_has_max();
  void set_has_min();
  void clear_has_min();
  void set_has_sum();
  void clear_has_sum();
  void set_has_avg();
  void clear_has_avg();
  void set_has_num();
  void clear_has_num();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  double max_;
  double sum_;
  double avg_;
  ::google::protobuf::int32 num_;
  double min_;
  friend struct ::protobuf_modules_2fplanning_2fproto_2fplanning_5fstats_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PlanningStats : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.planning.PlanningStats) */ {
 public:
  PlanningStats();
  virtual ~PlanningStats();

  PlanningStats(const PlanningStats& from);

  inline PlanningStats& operator=(const PlanningStats& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PlanningStats(PlanningStats&& from) noexcept
    : PlanningStats() {
    *this = ::std::move(from);
  }

  inline PlanningStats& operator=(PlanningStats&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlanningStats& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlanningStats* internal_default_instance() {
    return reinterpret_cast<const PlanningStats*>(
               &_PlanningStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(PlanningStats* other);
  friend void swap(PlanningStats& a, PlanningStats& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PlanningStats* New() const final {
    return CreateMaybeMessage<PlanningStats>(NULL);
  }

  PlanningStats* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PlanningStats>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PlanningStats& from);
  void MergeFrom(const PlanningStats& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlanningStats* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.planning.StatsGroup total_path_length = 1;
  bool has_total_path_length() const;
  void clear_total_path_length();
  static const int kTotalPathLengthFieldNumber = 1;
  private:
  const ::apollo::planning::StatsGroup& _internal_total_path_length() const;
  public:
  const ::apollo::planning::StatsGroup& total_path_length() const;
  ::apollo::planning::StatsGroup* release_total_path_length();
  ::apollo::planning::StatsGroup* mutable_total_path_length();
  void set_allocated_total_path_length(::apollo::planning::StatsGroup* total_path_length);

  // optional .apollo.planning.StatsGroup total_path_time = 2;
  bool has_total_path_time() const;
  void clear_total_path_time();
  static const int kTotalPathTimeFieldNumber = 2;
  private:
  const ::apollo::planning::StatsGroup& _internal_total_path_time() const;
  public:
  const ::apollo::planning::StatsGroup& total_path_time() const;
  ::apollo::planning::StatsGroup* release_total_path_time();
  ::apollo::planning::StatsGroup* mutable_total_path_time();
  void set_allocated_total_path_time(::apollo::planning::StatsGroup* total_path_time);

  // optional .apollo.planning.StatsGroup v = 3;
  bool has_v() const;
  void clear_v();
  static const int kVFieldNumber = 3;
  private:
  const ::apollo::planning::StatsGroup& _internal_v() const;
  public:
  const ::apollo::planning::StatsGroup& v() const;
  ::apollo::planning::StatsGroup* release_v();
  ::apollo::planning::StatsGroup* mutable_v();
  void set_allocated_v(::apollo::planning::StatsGroup* v);

  // optional .apollo.planning.StatsGroup a = 4;
  bool has_a() const;
  void clear_a();
  static const int kAFieldNumber = 4;
  private:
  const ::apollo::planning::StatsGroup& _internal_a() const;
  public:
  const ::apollo::planning::StatsGroup& a() const;
  ::apollo::planning::StatsGroup* release_a();
  ::apollo::planning::StatsGroup* mutable_a();
  void set_allocated_a(::apollo::planning::StatsGroup* a);

  // optional .apollo.planning.StatsGroup kappa = 5;
  bool has_kappa() const;
  void clear_kappa();
  static const int kKappaFieldNumber = 5;
  private:
  const ::apollo::planning::StatsGroup& _internal_kappa() const;
  public:
  const ::apollo::planning::StatsGroup& kappa() const;
  ::apollo::planning::StatsGroup* release_kappa();
  ::apollo::planning::StatsGroup* mutable_kappa();
  void set_allocated_kappa(::apollo::planning::StatsGroup* kappa);

  // optional .apollo.planning.StatsGroup dkappa = 6;
  bool has_dkappa() const;
  void clear_dkappa();
  static const int kDkappaFieldNumber = 6;
  private:
  const ::apollo::planning::StatsGroup& _internal_dkappa() const;
  public:
  const ::apollo::planning::StatsGroup& dkappa() const;
  ::apollo::planning::StatsGroup* release_dkappa();
  ::apollo::planning::StatsGroup* mutable_dkappa();
  void set_allocated_dkappa(::apollo::planning::StatsGroup* dkappa);

  // @@protoc_insertion_point(class_scope:apollo.planning.PlanningStats)
 private:
  void set_has_total_path_length();
  void clear_has_total_path_length();
  void set_has_total_path_time();
  void clear_has_total_path_time();
  void set_has_v();
  void clear_has_v();
  void set_has_a();
  void clear_has_a();
  void set_has_kappa();
  void clear_has_kappa();
  void set_has_dkappa();
  void clear_has_dkappa();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::apollo::planning::StatsGroup* total_path_length_;
  ::apollo::planning::StatsGroup* total_path_time_;
  ::apollo::planning::StatsGroup* v_;
  ::apollo::planning::StatsGroup* a_;
  ::apollo::planning::StatsGroup* kappa_;
  ::apollo::planning::StatsGroup* dkappa_;
  friend struct ::protobuf_modules_2fplanning_2fproto_2fplanning_5fstats_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StatsGroup

// optional double max = 1;
inline bool StatsGroup::has_max() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StatsGroup::set_has_max() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StatsGroup::clear_has_max() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StatsGroup::clear_max() {
  max_ = 0;
  clear_has_max();
}
inline double StatsGroup::max() const {
  // @@protoc_insertion_point(field_get:apollo.planning.StatsGroup.max)
  return max_;
}
inline void StatsGroup::set_max(double value) {
  set_has_max();
  max_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning.StatsGroup.max)
}

// optional double min = 2 [default = 10000000000];
inline bool StatsGroup::has_min() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void StatsGroup::set_has_min() {
  _has_bits_[0] |= 0x00000010u;
}
inline void StatsGroup::clear_has_min() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void StatsGroup::clear_min() {
  min_ = 10000000000;
  clear_has_min();
}
inline double StatsGroup::min() const {
  // @@protoc_insertion_point(field_get:apollo.planning.StatsGroup.min)
  return min_;
}
inline void StatsGroup::set_min(double value) {
  set_has_min();
  min_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning.StatsGroup.min)
}

// optional double sum = 3;
inline bool StatsGroup::has_sum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StatsGroup::set_has_sum() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StatsGroup::clear_has_sum() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StatsGroup::clear_sum() {
  sum_ = 0;
  clear_has_sum();
}
inline double StatsGroup::sum() const {
  // @@protoc_insertion_point(field_get:apollo.planning.StatsGroup.sum)
  return sum_;
}
inline void StatsGroup::set_sum(double value) {
  set_has_sum();
  sum_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning.StatsGroup.sum)
}

// optional double avg = 4;
inline bool StatsGroup::has_avg() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void StatsGroup::set_has_avg() {
  _has_bits_[0] |= 0x00000004u;
}
inline void StatsGroup::clear_has_avg() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void StatsGroup::clear_avg() {
  avg_ = 0;
  clear_has_avg();
}
inline double StatsGroup::avg() const {
  // @@protoc_insertion_point(field_get:apollo.planning.StatsGroup.avg)
  return avg_;
}
inline void StatsGroup::set_avg(double value) {
  set_has_avg();
  avg_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning.StatsGroup.avg)
}

// optional int32 num = 5;
inline bool StatsGroup::has_num() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void StatsGroup::set_has_num() {
  _has_bits_[0] |= 0x00000008u;
}
inline void StatsGroup::clear_has_num() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void StatsGroup::clear_num() {
  num_ = 0;
  clear_has_num();
}
inline ::google::protobuf::int32 StatsGroup::num() const {
  // @@protoc_insertion_point(field_get:apollo.planning.StatsGroup.num)
  return num_;
}
inline void StatsGroup::set_num(::google::protobuf::int32 value) {
  set_has_num();
  num_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning.StatsGroup.num)
}

// -------------------------------------------------------------------

// PlanningStats

// optional .apollo.planning.StatsGroup total_path_length = 1;
inline bool PlanningStats::has_total_path_length() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlanningStats::set_has_total_path_length() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlanningStats::clear_has_total_path_length() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlanningStats::clear_total_path_length() {
  if (total_path_length_ != NULL) total_path_length_->Clear();
  clear_has_total_path_length();
}
inline const ::apollo::planning::StatsGroup& PlanningStats::_internal_total_path_length() const {
  return *total_path_length_;
}
inline const ::apollo::planning::StatsGroup& PlanningStats::total_path_length() const {
  const ::apollo::planning::StatsGroup* p = total_path_length_;
  // @@protoc_insertion_point(field_get:apollo.planning.PlanningStats.total_path_length)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::planning::StatsGroup*>(
      &::apollo::planning::_StatsGroup_default_instance_);
}
inline ::apollo::planning::StatsGroup* PlanningStats::release_total_path_length() {
  // @@protoc_insertion_point(field_release:apollo.planning.PlanningStats.total_path_length)
  clear_has_total_path_length();
  ::apollo::planning::StatsGroup* temp = total_path_length_;
  total_path_length_ = NULL;
  return temp;
}
inline ::apollo::planning::StatsGroup* PlanningStats::mutable_total_path_length() {
  set_has_total_path_length();
  if (total_path_length_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::planning::StatsGroup>(GetArenaNoVirtual());
    total_path_length_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning.PlanningStats.total_path_length)
  return total_path_length_;
}
inline void PlanningStats::set_allocated_total_path_length(::apollo::planning::StatsGroup* total_path_length) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete total_path_length_;
  }
  if (total_path_length) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      total_path_length = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, total_path_length, submessage_arena);
    }
    set_has_total_path_length();
  } else {
    clear_has_total_path_length();
  }
  total_path_length_ = total_path_length;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning.PlanningStats.total_path_length)
}

// optional .apollo.planning.StatsGroup total_path_time = 2;
inline bool PlanningStats::has_total_path_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PlanningStats::set_has_total_path_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PlanningStats::clear_has_total_path_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PlanningStats::clear_total_path_time() {
  if (total_path_time_ != NULL) total_path_time_->Clear();
  clear_has_total_path_time();
}
inline const ::apollo::planning::StatsGroup& PlanningStats::_internal_total_path_time() const {
  return *total_path_time_;
}
inline const ::apollo::planning::StatsGroup& PlanningStats::total_path_time() const {
  const ::apollo::planning::StatsGroup* p = total_path_time_;
  // @@protoc_insertion_point(field_get:apollo.planning.PlanningStats.total_path_time)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::planning::StatsGroup*>(
      &::apollo::planning::_StatsGroup_default_instance_);
}
inline ::apollo::planning::StatsGroup* PlanningStats::release_total_path_time() {
  // @@protoc_insertion_point(field_release:apollo.planning.PlanningStats.total_path_time)
  clear_has_total_path_time();
  ::apollo::planning::StatsGroup* temp = total_path_time_;
  total_path_time_ = NULL;
  return temp;
}
inline ::apollo::planning::StatsGroup* PlanningStats::mutable_total_path_time() {
  set_has_total_path_time();
  if (total_path_time_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::planning::StatsGroup>(GetArenaNoVirtual());
    total_path_time_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning.PlanningStats.total_path_time)
  return total_path_time_;
}
inline void PlanningStats::set_allocated_total_path_time(::apollo::planning::StatsGroup* total_path_time) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete total_path_time_;
  }
  if (total_path_time) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      total_path_time = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, total_path_time, submessage_arena);
    }
    set_has_total_path_time();
  } else {
    clear_has_total_path_time();
  }
  total_path_time_ = total_path_time;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning.PlanningStats.total_path_time)
}

// optional .apollo.planning.StatsGroup v = 3;
inline bool PlanningStats::has_v() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PlanningStats::set_has_v() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PlanningStats::clear_has_v() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PlanningStats::clear_v() {
  if (v_ != NULL) v_->Clear();
  clear_has_v();
}
inline const ::apollo::planning::StatsGroup& PlanningStats::_internal_v() const {
  return *v_;
}
inline const ::apollo::planning::StatsGroup& PlanningStats::v() const {
  const ::apollo::planning::StatsGroup* p = v_;
  // @@protoc_insertion_point(field_get:apollo.planning.PlanningStats.v)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::planning::StatsGroup*>(
      &::apollo::planning::_StatsGroup_default_instance_);
}
inline ::apollo::planning::StatsGroup* PlanningStats::release_v() {
  // @@protoc_insertion_point(field_release:apollo.planning.PlanningStats.v)
  clear_has_v();
  ::apollo::planning::StatsGroup* temp = v_;
  v_ = NULL;
  return temp;
}
inline ::apollo::planning::StatsGroup* PlanningStats::mutable_v() {
  set_has_v();
  if (v_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::planning::StatsGroup>(GetArenaNoVirtual());
    v_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning.PlanningStats.v)
  return v_;
}
inline void PlanningStats::set_allocated_v(::apollo::planning::StatsGroup* v) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete v_;
  }
  if (v) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      v = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, v, submessage_arena);
    }
    set_has_v();
  } else {
    clear_has_v();
  }
  v_ = v;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning.PlanningStats.v)
}

// optional .apollo.planning.StatsGroup a = 4;
inline bool PlanningStats::has_a() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PlanningStats::set_has_a() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PlanningStats::clear_has_a() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PlanningStats::clear_a() {
  if (a_ != NULL) a_->Clear();
  clear_has_a();
}
inline const ::apollo::planning::StatsGroup& PlanningStats::_internal_a() const {
  return *a_;
}
inline const ::apollo::planning::StatsGroup& PlanningStats::a() const {
  const ::apollo::planning::StatsGroup* p = a_;
  // @@protoc_insertion_point(field_get:apollo.planning.PlanningStats.a)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::planning::StatsGroup*>(
      &::apollo::planning::_StatsGroup_default_instance_);
}
inline ::apollo::planning::StatsGroup* PlanningStats::release_a() {
  // @@protoc_insertion_point(field_release:apollo.planning.PlanningStats.a)
  clear_has_a();
  ::apollo::planning::StatsGroup* temp = a_;
  a_ = NULL;
  return temp;
}
inline ::apollo::planning::StatsGroup* PlanningStats::mutable_a() {
  set_has_a();
  if (a_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::planning::StatsGroup>(GetArenaNoVirtual());
    a_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning.PlanningStats.a)
  return a_;
}
inline void PlanningStats::set_allocated_a(::apollo::planning::StatsGroup* a) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete a_;
  }
  if (a) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      a = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, a, submessage_arena);
    }
    set_has_a();
  } else {
    clear_has_a();
  }
  a_ = a;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning.PlanningStats.a)
}

// optional .apollo.planning.StatsGroup kappa = 5;
inline bool PlanningStats::has_kappa() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PlanningStats::set_has_kappa() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PlanningStats::clear_has_kappa() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PlanningStats::clear_kappa() {
  if (kappa_ != NULL) kappa_->Clear();
  clear_has_kappa();
}
inline const ::apollo::planning::StatsGroup& PlanningStats::_internal_kappa() const {
  return *kappa_;
}
inline const ::apollo::planning::StatsGroup& PlanningStats::kappa() const {
  const ::apollo::planning::StatsGroup* p = kappa_;
  // @@protoc_insertion_point(field_get:apollo.planning.PlanningStats.kappa)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::planning::StatsGroup*>(
      &::apollo::planning::_StatsGroup_default_instance_);
}
inline ::apollo::planning::StatsGroup* PlanningStats::release_kappa() {
  // @@protoc_insertion_point(field_release:apollo.planning.PlanningStats.kappa)
  clear_has_kappa();
  ::apollo::planning::StatsGroup* temp = kappa_;
  kappa_ = NULL;
  return temp;
}
inline ::apollo::planning::StatsGroup* PlanningStats::mutable_kappa() {
  set_has_kappa();
  if (kappa_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::planning::StatsGroup>(GetArenaNoVirtual());
    kappa_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning.PlanningStats.kappa)
  return kappa_;
}
inline void PlanningStats::set_allocated_kappa(::apollo::planning::StatsGroup* kappa) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete kappa_;
  }
  if (kappa) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      kappa = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, kappa, submessage_arena);
    }
    set_has_kappa();
  } else {
    clear_has_kappa();
  }
  kappa_ = kappa;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning.PlanningStats.kappa)
}

// optional .apollo.planning.StatsGroup dkappa = 6;
inline bool PlanningStats::has_dkappa() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PlanningStats::set_has_dkappa() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PlanningStats::clear_has_dkappa() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PlanningStats::clear_dkappa() {
  if (dkappa_ != NULL) dkappa_->Clear();
  clear_has_dkappa();
}
inline const ::apollo::planning::StatsGroup& PlanningStats::_internal_dkappa() const {
  return *dkappa_;
}
inline const ::apollo::planning::StatsGroup& PlanningStats::dkappa() const {
  const ::apollo::planning::StatsGroup* p = dkappa_;
  // @@protoc_insertion_point(field_get:apollo.planning.PlanningStats.dkappa)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::planning::StatsGroup*>(
      &::apollo::planning::_StatsGroup_default_instance_);
}
inline ::apollo::planning::StatsGroup* PlanningStats::release_dkappa() {
  // @@protoc_insertion_point(field_release:apollo.planning.PlanningStats.dkappa)
  clear_has_dkappa();
  ::apollo::planning::StatsGroup* temp = dkappa_;
  dkappa_ = NULL;
  return temp;
}
inline ::apollo::planning::StatsGroup* PlanningStats::mutable_dkappa() {
  set_has_dkappa();
  if (dkappa_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::planning::StatsGroup>(GetArenaNoVirtual());
    dkappa_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning.PlanningStats.dkappa)
  return dkappa_;
}
inline void PlanningStats::set_allocated_dkappa(::apollo::planning::StatsGroup* dkappa) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete dkappa_;
  }
  if (dkappa) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      dkappa = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, dkappa, submessage_arena);
    }
    set_has_dkappa();
  } else {
    clear_has_dkappa();
  }
  dkappa_ = dkappa;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning.PlanningStats.dkappa)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace planning
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_modules_2fplanning_2fproto_2fplanning_5fstats_2eproto
