// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/planning/proto/st_drivable_boundary.proto

#ifndef PROTOBUF_INCLUDED_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto
#define PROTOBUF_INCLUDED_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto 

namespace protobuf_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto
namespace apollo {
namespace planning {
class STDrivableBoundary;
class STDrivableBoundaryDefaultTypeInternal;
extern STDrivableBoundaryDefaultTypeInternal _STDrivableBoundary_default_instance_;
class STDrivableBoundaryInstance;
class STDrivableBoundaryInstanceDefaultTypeInternal;
extern STDrivableBoundaryInstanceDefaultTypeInternal _STDrivableBoundaryInstance_default_instance_;
}  // namespace planning
}  // namespace apollo
namespace google {
namespace protobuf {
template<> ::apollo::planning::STDrivableBoundary* Arena::CreateMaybeMessage<::apollo::planning::STDrivableBoundary>(Arena*);
template<> ::apollo::planning::STDrivableBoundaryInstance* Arena::CreateMaybeMessage<::apollo::planning::STDrivableBoundaryInstance>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace apollo {
namespace planning {

// ===================================================================

class STDrivableBoundaryInstance : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.planning.STDrivableBoundaryInstance) */ {
 public:
  STDrivableBoundaryInstance();
  virtual ~STDrivableBoundaryInstance();

  STDrivableBoundaryInstance(const STDrivableBoundaryInstance& from);

  inline STDrivableBoundaryInstance& operator=(const STDrivableBoundaryInstance& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  STDrivableBoundaryInstance(STDrivableBoundaryInstance&& from) noexcept
    : STDrivableBoundaryInstance() {
    *this = ::std::move(from);
  }

  inline STDrivableBoundaryInstance& operator=(STDrivableBoundaryInstance&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const STDrivableBoundaryInstance& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const STDrivableBoundaryInstance* internal_default_instance() {
    return reinterpret_cast<const STDrivableBoundaryInstance*>(
               &_STDrivableBoundaryInstance_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(STDrivableBoundaryInstance* other);
  friend void swap(STDrivableBoundaryInstance& a, STDrivableBoundaryInstance& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline STDrivableBoundaryInstance* New() const final {
    return CreateMaybeMessage<STDrivableBoundaryInstance>(NULL);
  }

  STDrivableBoundaryInstance* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<STDrivableBoundaryInstance>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const STDrivableBoundaryInstance& from);
  void MergeFrom(const STDrivableBoundaryInstance& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(STDrivableBoundaryInstance* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double t = 1;
  bool has_t() const;
  void clear_t();
  static const int kTFieldNumber = 1;
  double t() const;
  void set_t(double value);

  // optional double s_lower = 2;
  bool has_s_lower() const;
  void clear_s_lower();
  static const int kSLowerFieldNumber = 2;
  double s_lower() const;
  void set_s_lower(double value);

  // optional double s_upper = 3;
  bool has_s_upper() const;
  void clear_s_upper();
  static const int kSUpperFieldNumber = 3;
  double s_upper() const;
  void set_s_upper(double value);

  // optional double v_obs_lower = 4;
  bool has_v_obs_lower() const;
  void clear_v_obs_lower();
  static const int kVObsLowerFieldNumber = 4;
  double v_obs_lower() const;
  void set_v_obs_lower(double value);

  // optional double v_obs_upper = 5;
  bool has_v_obs_upper() const;
  void clear_v_obs_upper();
  static const int kVObsUpperFieldNumber = 5;
  double v_obs_upper() const;
  void set_v_obs_upper(double value);

  // @@protoc_insertion_point(class_scope:apollo.planning.STDrivableBoundaryInstance)
 private:
  void set_has_t();
  void clear_has_t();
  void set_has_s_lower();
  void clear_has_s_lower();
  void set_has_s_upper();
  void clear_has_s_upper();
  void set_has_v_obs_lower();
  void clear_has_v_obs_lower();
  void set_has_v_obs_upper();
  void clear_has_v_obs_upper();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  double t_;
  double s_lower_;
  double s_upper_;
  double v_obs_lower_;
  double v_obs_upper_;
  friend struct ::protobuf_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class STDrivableBoundary : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.planning.STDrivableBoundary) */ {
 public:
  STDrivableBoundary();
  virtual ~STDrivableBoundary();

  STDrivableBoundary(const STDrivableBoundary& from);

  inline STDrivableBoundary& operator=(const STDrivableBoundary& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  STDrivableBoundary(STDrivableBoundary&& from) noexcept
    : STDrivableBoundary() {
    *this = ::std::move(from);
  }

  inline STDrivableBoundary& operator=(STDrivableBoundary&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const STDrivableBoundary& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const STDrivableBoundary* internal_default_instance() {
    return reinterpret_cast<const STDrivableBoundary*>(
               &_STDrivableBoundary_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(STDrivableBoundary* other);
  friend void swap(STDrivableBoundary& a, STDrivableBoundary& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline STDrivableBoundary* New() const final {
    return CreateMaybeMessage<STDrivableBoundary>(NULL);
  }

  STDrivableBoundary* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<STDrivableBoundary>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const STDrivableBoundary& from);
  void MergeFrom(const STDrivableBoundary& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(STDrivableBoundary* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.planning.STDrivableBoundaryInstance st_boundary = 1;
  int st_boundary_size() const;
  void clear_st_boundary();
  static const int kStBoundaryFieldNumber = 1;
  ::apollo::planning::STDrivableBoundaryInstance* mutable_st_boundary(int index);
  ::google::protobuf::RepeatedPtrField< ::apollo::planning::STDrivableBoundaryInstance >*
      mutable_st_boundary();
  const ::apollo::planning::STDrivableBoundaryInstance& st_boundary(int index) const;
  ::apollo::planning::STDrivableBoundaryInstance* add_st_boundary();
  const ::google::protobuf::RepeatedPtrField< ::apollo::planning::STDrivableBoundaryInstance >&
      st_boundary() const;

  // @@protoc_insertion_point(class_scope:apollo.planning.STDrivableBoundary)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::planning::STDrivableBoundaryInstance > st_boundary_;
  friend struct ::protobuf_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// STDrivableBoundaryInstance

// optional double t = 1;
inline bool STDrivableBoundaryInstance::has_t() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void STDrivableBoundaryInstance::set_has_t() {
  _has_bits_[0] |= 0x00000001u;
}
inline void STDrivableBoundaryInstance::clear_has_t() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void STDrivableBoundaryInstance::clear_t() {
  t_ = 0;
  clear_has_t();
}
inline double STDrivableBoundaryInstance::t() const {
  // @@protoc_insertion_point(field_get:apollo.planning.STDrivableBoundaryInstance.t)
  return t_;
}
inline void STDrivableBoundaryInstance::set_t(double value) {
  set_has_t();
  t_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning.STDrivableBoundaryInstance.t)
}

// optional double s_lower = 2;
inline bool STDrivableBoundaryInstance::has_s_lower() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void STDrivableBoundaryInstance::set_has_s_lower() {
  _has_bits_[0] |= 0x00000002u;
}
inline void STDrivableBoundaryInstance::clear_has_s_lower() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void STDrivableBoundaryInstance::clear_s_lower() {
  s_lower_ = 0;
  clear_has_s_lower();
}
inline double STDrivableBoundaryInstance::s_lower() const {
  // @@protoc_insertion_point(field_get:apollo.planning.STDrivableBoundaryInstance.s_lower)
  return s_lower_;
}
inline void STDrivableBoundaryInstance::set_s_lower(double value) {
  set_has_s_lower();
  s_lower_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning.STDrivableBoundaryInstance.s_lower)
}

// optional double s_upper = 3;
inline bool STDrivableBoundaryInstance::has_s_upper() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void STDrivableBoundaryInstance::set_has_s_upper() {
  _has_bits_[0] |= 0x00000004u;
}
inline void STDrivableBoundaryInstance::clear_has_s_upper() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void STDrivableBoundaryInstance::clear_s_upper() {
  s_upper_ = 0;
  clear_has_s_upper();
}
inline double STDrivableBoundaryInstance::s_upper() const {
  // @@protoc_insertion_point(field_get:apollo.planning.STDrivableBoundaryInstance.s_upper)
  return s_upper_;
}
inline void STDrivableBoundaryInstance::set_s_upper(double value) {
  set_has_s_upper();
  s_upper_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning.STDrivableBoundaryInstance.s_upper)
}

// optional double v_obs_lower = 4;
inline bool STDrivableBoundaryInstance::has_v_obs_lower() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void STDrivableBoundaryInstance::set_has_v_obs_lower() {
  _has_bits_[0] |= 0x00000008u;
}
inline void STDrivableBoundaryInstance::clear_has_v_obs_lower() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void STDrivableBoundaryInstance::clear_v_obs_lower() {
  v_obs_lower_ = 0;
  clear_has_v_obs_lower();
}
inline double STDrivableBoundaryInstance::v_obs_lower() const {
  // @@protoc_insertion_point(field_get:apollo.planning.STDrivableBoundaryInstance.v_obs_lower)
  return v_obs_lower_;
}
inline void STDrivableBoundaryInstance::set_v_obs_lower(double value) {
  set_has_v_obs_lower();
  v_obs_lower_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning.STDrivableBoundaryInstance.v_obs_lower)
}

// optional double v_obs_upper = 5;
inline bool STDrivableBoundaryInstance::has_v_obs_upper() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void STDrivableBoundaryInstance::set_has_v_obs_upper() {
  _has_bits_[0] |= 0x00000010u;
}
inline void STDrivableBoundaryInstance::clear_has_v_obs_upper() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void STDrivableBoundaryInstance::clear_v_obs_upper() {
  v_obs_upper_ = 0;
  clear_has_v_obs_upper();
}
inline double STDrivableBoundaryInstance::v_obs_upper() const {
  // @@protoc_insertion_point(field_get:apollo.planning.STDrivableBoundaryInstance.v_obs_upper)
  return v_obs_upper_;
}
inline void STDrivableBoundaryInstance::set_v_obs_upper(double value) {
  set_has_v_obs_upper();
  v_obs_upper_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning.STDrivableBoundaryInstance.v_obs_upper)
}

// -------------------------------------------------------------------

// STDrivableBoundary

// repeated .apollo.planning.STDrivableBoundaryInstance st_boundary = 1;
inline int STDrivableBoundary::st_boundary_size() const {
  return st_boundary_.size();
}
inline void STDrivableBoundary::clear_st_boundary() {
  st_boundary_.Clear();
}
inline ::apollo::planning::STDrivableBoundaryInstance* STDrivableBoundary::mutable_st_boundary(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.planning.STDrivableBoundary.st_boundary)
  return st_boundary_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::planning::STDrivableBoundaryInstance >*
STDrivableBoundary::mutable_st_boundary() {
  // @@protoc_insertion_point(field_mutable_list:apollo.planning.STDrivableBoundary.st_boundary)
  return &st_boundary_;
}
inline const ::apollo::planning::STDrivableBoundaryInstance& STDrivableBoundary::st_boundary(int index) const {
  // @@protoc_insertion_point(field_get:apollo.planning.STDrivableBoundary.st_boundary)
  return st_boundary_.Get(index);
}
inline ::apollo::planning::STDrivableBoundaryInstance* STDrivableBoundary::add_st_boundary() {
  // @@protoc_insertion_point(field_add:apollo.planning.STDrivableBoundary.st_boundary)
  return st_boundary_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::planning::STDrivableBoundaryInstance >&
STDrivableBoundary::st_boundary() const {
  // @@protoc_insertion_point(field_list:apollo.planning.STDrivableBoundary.st_boundary)
  return st_boundary_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace planning
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto
